name: ui_flutter
description: "Kellogg Music Match Flutter app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon-512x512.png"
  adaptive_icon_foreground: "assets/icons/icon-512x512.png"
  adaptive_icon_background: "#ffffff"
