#!/usr/bin/env python3
"""
Load MusicBrainz artists data into PostgreSQL database.
This script reads the CSV file generated by fetch_musicbrainz_artists.py
and populates the artists table with reference data.

Fixed version with better error handling and transaction management.
"""

import csv
import psycopg2
import argparse
import sys
from datetime import datetime
from typing import Optional

class MusicBrainzLoader:
    def __init__(self, connection_string: str):
        self.connection_string = connection_string
        self.connection = None
        
    def connect(self):
        """Connect to PostgreSQL database."""
        try:
            self.connection = psycopg2.connect(self.connection_string)
            # Use autocommit for individual artist operations
            self.connection.autocommit = True
            print("Connected to PostgreSQL database")
        except Exception as e:
            print(f"Error connecting to database: {e}")
            sys.exit(1)
    
    def disconnect(self):
        """Disconnect from database."""
        if self.connection:
            self.connection.close()
            print("Disconnected from database")
    
    def parse_date(self, date_str: str) -> Optional[str]:
        """Parse MusicBrainz date format to PostgreSQL date."""
        if not date_str or date_str.strip() == '':
            return None
        
        # MusicBrainz dates can be YYYY, YYYY-MM, or YYYY-MM-DD
        date_str = date_str.strip()
        
        if len(date_str) == 4:  # YYYY
            return f"{date_str}-01-01"
        elif len(date_str) == 7:  # YYYY-MM
            return f"{date_str}-01"
        elif len(date_str) == 10:  # YYYY-MM-DD
            return date_str
        else:
            return None
    
    def clean_value(self, value: str) -> Optional[str]:
        """Clean and validate field values."""
        if not value or value.strip() == '':
            return None
        return value.strip()
    
    def load_artists_from_csv(self, csv_file: str, batch_size: int = 1000):
        """Load artists from CSV file into database."""
        if not self.connection:
            self.connect()
        
        cursor = self.connection.cursor()
        total_processed = 0
        total_inserted = 0
        total_updated = 0
        total_errors = 0
        
        try:
            print(f"Loading MusicBrainz artists from {csv_file}")
            
            with open(csv_file, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                
                for row in reader:
                    # Parse and clean the row data
                    artist_data = {
                        'name': self.clean_value(row['name']),
                        'musicbrainz_id': self.clean_value(row['id']) if row['id'] else None,
                        'sort_name': self.clean_value(row['sort_name']),
                        'artist_type': self.clean_value(row['type']),
                        'gender': self.clean_value(row['gender']),
                        'country': self.clean_value(row['country']),
                        'life_span_begin': self.parse_date(row['life_span_begin']),
                        'life_span_end': self.parse_date(row['life_span_end']),
                        'disambiguation': self.clean_value(row['disambiguation']),
                        'musicbrainz_score': int(row['score']) if row['score'] else None
                    }
                    
                    # Skip if no name
                    if not artist_data['name']:
                        continue
                    
                    # Process each artist individually with error handling
                    try:
                        artist_id = self.insert_artist(cursor, artist_data)
                        if artist_id:
                            total_inserted += 1
                        else:
                            total_updated += 1
                        
                        total_processed += 1
                        
                        # Progress report
                        if total_processed % 1000 == 0:
                            print(f"Processed {total_processed} artists (inserted: {total_inserted}, updated: {total_updated}, errors: {total_errors})")
                        
                    except Exception as e:
                        total_errors += 1
                        if total_errors <= 10:  # Only show first 10 errors to avoid spam
                            print(f"Error processing artist '{artist_data['name']}': {e}")
                        elif total_errors == 11:
                            print(f"More errors occurred... (showing only first 10)")
                        continue
            
            print(f"\nSuccessfully processed {total_processed} artists")
            print(f"  - Inserted: {total_inserted}")
            print(f"  - Updated: {total_updated}")
            print(f"  - Errors: {total_errors}")
            
        except Exception as e:
            print(f"Error loading artists: {e}")
            raise
        finally:
            cursor.close()
    
    def insert_artist(self, cursor, artist_data):
        """Insert a single artist using the upsert function."""
        cursor.execute("""
            SELECT upsert_artist_with_musicbrainz(
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
            )
        """, (
            artist_data['name'],
            artist_data['musicbrainz_id'],
            artist_data['sort_name'],
            artist_data['artist_type'],
            artist_data['gender'],
            artist_data['country'],
            artist_data['life_span_begin'],
            artist_data['life_span_end'],
            artist_data['disambiguation'],
            artist_data['musicbrainz_score'],
            True  # is_reference
        ))
        
        result = cursor.fetchone()
        return result[0] if result else None
    
    def get_statistics(self):
        """Get statistics about loaded artists."""
        if not self.connection:
            self.connect()
        
        cursor = self.connection.cursor()
        
        try:
            # Total artists
            cursor.execute("SELECT COUNT(*) FROM artists")
            total_artists = cursor.fetchone()[0]
            
            # Reference artists
            cursor.execute("SELECT COUNT(*) FROM artists WHERE is_reference = TRUE")
            reference_artists = cursor.fetchone()[0]
            
            # User artists
            cursor.execute("SELECT COUNT(*) FROM artists WHERE is_reference = FALSE")
            user_artists = cursor.fetchone()[0]
            
            # Top countries
            cursor.execute("""
                SELECT country, COUNT(*) as count 
                FROM artists 
                WHERE country IS NOT NULL AND is_reference = TRUE
                GROUP BY country 
                ORDER BY count DESC 
                LIMIT 10
            """)
            top_countries = cursor.fetchall()
            
            # Top artist types
            cursor.execute("""
                SELECT artist_type, COUNT(*) as count 
                FROM artists 
                WHERE artist_type IS NOT NULL AND is_reference = TRUE
                GROUP BY artist_type 
                ORDER BY count DESC
            """)
            top_types = cursor.fetchall()
            
            print(f"\nDatabase Statistics:")
            print(f"  Total artists: {total_artists:,}")
            print(f"  Reference artists (MusicBrainz): {reference_artists:,}")
            print(f"  User-submitted artists: {user_artists:,}")
            
            if top_countries:
                print(f"\nTop Countries:")
                for country, count in top_countries:
                    print(f"  {country}: {count:,}")
            
            if top_types:
                print(f"\nTop Artist Types:")
                for artist_type, count in top_types:
                    print(f"  {artist_type}: {count:,}")
                
        except Exception as e:
            print(f"Error getting statistics: {e}")
        finally:
            cursor.close()

def main():
    parser = argparse.ArgumentParser(description='Load MusicBrainz artists into PostgreSQL')
    parser.add_argument('csv_file', help='Path to MusicBrainz artists CSV file')
    parser.add_argument('--connection-string', 
                       default='postgresql://kellogg_user:kellogg_secure_pass_2024@localhost:5432/kellogg_music_match',
                       help='PostgreSQL connection string')
    parser.add_argument('--batch-size', type=int, default=1000, help='Batch size for processing (not used in this version)')
    parser.add_argument('--stats-only', action='store_true', help='Only show statistics')
    
    args = parser.parse_args()
    
    loader = MusicBrainzLoader(args.connection_string)
    
    try:
        if args.stats_only:
            loader.get_statistics()
        else:
            loader.load_artists_from_csv(args.csv_file, args.batch_size)
            loader.get_statistics()
    finally:
        loader.disconnect()

if __name__ == "__main__":
    main()