// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Artists table containing both user-submitted and MusicBrainz reference artists
type Artist struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MusicbrainzID    pgtype.UUID        `json:"musicbrainz_id"`
	SortName         pgtype.Text        `json:"sort_name"`
	ArtistType       pgtype.Text        `json:"artist_type"`
	Gender           pgtype.Text        `json:"gender"`
	Country          pgtype.Text        `json:"country"`
	LifeSpanBegin    pgtype.Date        `json:"life_span_begin"`
	LifeSpanEnd      pgtype.Date        `json:"life_span_end"`
	Disambiguation   pgtype.Text        `json:"disambiguation"`
	MusicbrainzScore pgtype.Int4        `json:"musicbrainz_score"`
	IsReference      pgtype.Bool        `json:"is_reference"`
}

type ArtistListenerCount struct {
	ArtistID   int32 `json:"artist_id"`
	NListeners int64 `json:"n_listeners"`
}

type ArtistNeighbor struct {
	A         int32              `json:"a"`
	B         int32              `json:"b"`
	Distance  float64            `json:"distance"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Artists/performers separate from MusicBrainz artists table
type ConcertArtist struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Genres    []string         `json:"genres"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// Concert events fetched from external APIs like Ticketmaster
type ConcertEvent struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	EventDate      pgtype.Timestamp `json:"event_date"`
	VenueID        pgtype.Text      `json:"venue_id"`
	Genres         []string         `json:"genres"`
	PriceMin       pgtype.Numeric   `json:"price_min"`
	PriceMax       pgtype.Numeric   `json:"price_max"`
	PriceCurrency  pgtype.Text      `json:"price_currency"`
	TicketUrl      pgtype.Text      `json:"ticket_url"`
	Description    pgtype.Text      `json:"description"`
	Status         string           `json:"status"`
	AgeRestriction pgtype.Text      `json:"age_restriction"`
	// External API provider (ticketmaster, eventbrite, etc.)
	Provider string `json:"provider"`
	// Original URL from the external provider
	ExternalUrl pgtype.Text      `json:"external_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

// Many-to-many relationship between events and artists
type ConcertEventArtist struct {
	EventID   string           `json:"event_id"`
	ArtistID  string           `json:"artist_id"`
	Role      pgtype.Text      `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Feedback struct {
	ID           int32              `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	FeedbackText string             `json:"feedback_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      pgtype.Bool        `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReferenceArtist struct {
	ID               int32       `json:"id"`
	Name             string      `json:"name"`
	SortName         pgtype.Text `json:"sort_name"`
	ArtistType       pgtype.Text `json:"artist_type"`
	Gender           pgtype.Text `json:"gender"`
	Country          pgtype.Text `json:"country"`
	LifeSpanBegin    pgtype.Date `json:"life_span_begin"`
	LifeSpanEnd      pgtype.Date `json:"life_span_end"`
	Disambiguation   pgtype.Text `json:"disambiguation"`
	MusicbrainzScore pgtype.Int4 `json:"musicbrainz_score"`
	MusicbrainzID    pgtype.UUID `json:"musicbrainz_id"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	// MBA program type: 2Y, 1Y, MMM, MBAi, JD-MBA, MD-MBA, EWMBA, JV
	Program pgtype.Text `json:"program"`
	// Expected graduation year (current year to 2030)
	GraduationYear pgtype.Int4 `json:"graduation_year"`
}

type UserArtist struct {
	UserID    uuid.UUID          `json:"user_id"`
	ArtistID  int32              `json:"artist_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Rank      int16              `json:"rank"`
}

type UserSubmittedArtist struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Concert venues with location information
type Venue struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Street    pgtype.Text      `json:"street"`
	City      string           `json:"city"`
	State     pgtype.Text      `json:"state"`
	Country   string           `json:"country"`
	Postal    pgtype.Text      `json:"postal"`
	Capacity  pgtype.Int4      `json:"capacity"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
