// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

// Artists table containing both user-submitted and MusicBrainz reference artists
type Artist struct {
	ID               int32          `json:"id"`
	Name             string         `json:"name"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	MusicbrainzID    uuid.NullUUID  `json:"musicbrainz_id"`
	SortName         sql.NullString `json:"sort_name"`
	ArtistType       sql.NullString `json:"artist_type"`
	Gender           sql.NullString `json:"gender"`
	Country          sql.NullString `json:"country"`
	LifeSpanBegin    sql.NullTime   `json:"life_span_begin"`
	LifeSpanEnd      sql.NullTime   `json:"life_span_end"`
	Disambiguation   sql.NullString `json:"disambiguation"`
	MusicbrainzScore sql.NullInt32  `json:"musicbrainz_score"`
	IsReference      sql.NullBool   `json:"is_reference"`
}

type Feedback struct {
	ID           int32        `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	FeedbackText string       `json:"feedback_text"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type ReferenceArtist struct {
	ID               int32          `json:"id"`
	Name             string         `json:"name"`
	SortName         sql.NullString `json:"sort_name"`
	ArtistType       sql.NullString `json:"artist_type"`
	Gender           sql.NullString `json:"gender"`
	Country          sql.NullString `json:"country"`
	LifeSpanBegin    sql.NullTime   `json:"life_span_begin"`
	LifeSpanEnd      sql.NullTime   `json:"life_span_end"`
	Disambiguation   sql.NullString `json:"disambiguation"`
	MusicbrainzScore sql.NullInt32  `json:"musicbrainz_score"`
	MusicbrainzID    uuid.NullUUID  `json:"musicbrainz_id"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	// MBA program type: 2Y, 1Y, MBAi, MMM, EWMBA, JV
	Program sql.NullString `json:"program"`
	// Expected graduation year (current year to 2030)
	GraduationYear sql.NullInt32 `json:"graduation_year"`
}

type UserArtist struct {
	UserID    uuid.UUID    `json:"user_id"`
	ArtistID  int32        `json:"artist_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	Rank      int16        `json:"rank"`
}

type UserSubmittedArtist struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
