// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserArtist = `-- name: AddUserArtist :exec

INSERT INTO user_artists (user_id, artist_id, rank)
VALUES ($1::uuid, $2::int, $3::int)
ON CONFLICT (user_id, artist_id) DO UPDATE SET rank = EXCLUDED.rank
`

type AddUserArtistParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ArtistID int32     `json:"artist_id"`
	Rank     int32     `json:"rank"`
}

// =======================
// User-Artist relations
// =======================
// FIX: conflict target must be a unique/PK constraint. Your table has PK (user_id, artist_id)
func (q *Queries) AddUserArtist(ctx context.Context, arg AddUserArtistParams) error {
	_, err := q.db.Exec(ctx, addUserArtist, arg.UserID, arg.ArtistID, arg.Rank)
	return err
}

const chamferSimilarityByIDs = `-- name: ChamferSimilarityByIDs :one
SELECT chamfer_similarity_artists($1::int[], $2::int[]) AS similarity
`

type ChamferSimilarityByIDsParams struct {
	ArtistIdsList1 []int32 `json:"artist_ids_list1"`
	ArtistIdsList2 []int32 `json:"artist_ids_list2"`
}

func (q *Queries) ChamferSimilarityByIDs(ctx context.Context, arg ChamferSimilarityByIDsParams) (float64, error) {
	row := q.db.QueryRow(ctx, chamferSimilarityByIDs, arg.ArtistIdsList1, arg.ArtistIdsList2)
	var similarity float64
	err := row.Scan(&similarity)
	return similarity, err
}

const chamferSimilarityByNames = `-- name: ChamferSimilarityByNames :one
WITH s1 AS (
  SELECT COALESCE(array_agg(id), '{}'::int[]) AS ids
  FROM artists
  WHERE name = ANY($1::text[])
),
s2 AS (
  SELECT COALESCE(array_agg(id), '{}'::int[]) AS ids
  FROM artists
  WHERE name = ANY($2::text[])
)
SELECT chamfer_similarity_artists(
  (SELECT ids FROM s1),
  (SELECT ids FROM s2)
) AS similarity
`

type ChamferSimilarityByNamesParams struct {
	ArtistNamesList1 []string `json:"artist_names_list1"`
	ArtistNamesList2 []string `json:"artist_names_list2"`
}

func (q *Queries) ChamferSimilarityByNames(ctx context.Context, arg ChamferSimilarityByNamesParams) (float64, error) {
	row := q.db.QueryRow(ctx, chamferSimilarityByNames, arg.ArtistNamesList1, arg.ArtistNamesList2)
	var similarity float64
	err := row.Scan(&similarity)
	return similarity, err
}

const clearUserArtists = `-- name: ClearUserArtists :exec
DELETE FROM user_artists WHERE user_id = $1
`

func (q *Queries) ClearUserArtists(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserArtists, userID)
	return err
}

const createArtist = `-- name: CreateArtist :one

INSERT INTO artists (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at, musicbrainz_id, sort_name, artist_type, gender, country, life_span_begin, life_span_end, disambiguation, musicbrainz_score, is_reference
`

// =======================
// Artists
// =======================
func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.MusicbrainzID,
		&i.SortName,
		&i.ArtistType,
		&i.Gender,
		&i.Country,
		&i.LifeSpanBegin,
		&i.LifeSpanEnd,
		&i.Disambiguation,
		&i.MusicbrainzScore,
		&i.IsReference,
	)
	return i, err
}

const createFeedback = `-- name: CreateFeedback :one

INSERT INTO feedback (user_id, feedback_text)
VALUES ($1, $2)
RETURNING id, user_id, feedback_text, created_at, updated_at
`

type CreateFeedbackParams struct {
	UserID       uuid.UUID `json:"user_id"`
	FeedbackText string    `json:"feedback_text"`
}

// (If you also want the :by-user-id variant, keep your FindSimilarUsersChamferByUserID below unchanged.)
// Feedback queries
func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback, arg.UserID, arg.FeedbackText)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedbackText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, used, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// =======================
// Password Reset Tokens
// =======================
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, email, first_name, last_name, password_hash, program, graduation_year)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year
`

type CreateUserParams struct {
	ID             uuid.UUID   `json:"id"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	PasswordHash   string      `json:"password_hash"`
	Program        pgtype.Text `json:"program"`
	GraduationYear pgtype.Int4 `json:"graduation_year"`
}

// =======================
// Users
// =======================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.Program,
		arg.GraduationYear,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens 
WHERE expires_at < NOW() - INTERVAL '1 hour'
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteOldConcertEvents = `-- name: DeleteOldConcertEvents :exec
DELETE FROM concert_events 
WHERE event_date < $1
`

func (q *Queries) DeleteOldConcertEvents(ctx context.Context, cutoffDate pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteOldConcertEvents, cutoffDate)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserConcertEventInterest = `-- name: DeleteUserConcertEventInterest :exec
DELETE FROM user_concert_event_interest
WHERE user_id = $1 AND event_id = $2
`

type DeleteUserConcertEventInterestParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EventID string    `json:"event_id"`
}

func (q *Queries) DeleteUserConcertEventInterest(ctx context.Context, arg DeleteUserConcertEventInterestParams) error {
	_, err := q.db.Exec(ctx, deleteUserConcertEventInterest, arg.UserID, arg.EventID)
	return err
}

const deleteUserPasswordResetTokens = `-- name: DeleteUserPasswordResetTokens :exec
DELETE FROM password_reset_tokens 
WHERE user_id = $1
`

func (q *Queries) DeleteUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPasswordResetTokens, userID)
	return err
}

const findSimilarUsers = `-- name: FindSimilarUsers :many

WITH target AS (
  SELECT id AS target_id, program AS target_program, graduation_year AS target_grad
  FROM users
  WHERE users.username = $2
),
base_list AS (
  -- ensure target has at least one artist; otherwise return no rows
  SELECT 1 FROM user_artists ua JOIN target t ON ua.user_id = t.target_id LIMIT 1
),
target_artists AS (
  SELECT ua.artist_id
  FROM user_artists ua
  JOIN target t ON ua.user_id = t.target_id
),
candidates AS (
  -- users with at least one overlapping artist with the target
  SELECT ua.user_id AS candidate_id
  FROM user_artists ua
  JOIN target_artists ta USING (artist_id)
  GROUP BY ua.user_id
),
scored AS (
  SELECT
    u.id,
    u.username,
    u.first_name,
    u.last_name,
    u.program,
    u.graduation_year,
    s.d AS distance
  FROM users u
  JOIN candidates c ON c.candidate_id = u.id
  JOIN target t ON TRUE
  CROSS JOIN LATERAL (
    SELECT user_chamfer_distance(
             u.id,
             t.target_id,
             $1::int,     -- top_k
             $3::float8   -- alpha
           ) AS d
  ) AS s
  WHERE u.username <> $2
    AND EXISTS (SELECT 1 FROM base_list)
  ORDER BY
    s.d ASC,
    (u.program = t.target_program) DESC,
    (u.graduation_year = t.target_grad) DESC
  LIMIT $4
)
SELECT
  sc.username,
  sc.first_name,
  sc.last_name,
  sc.program,
  sc.graduation_year,
  COALESCE(al.artists, '{}'::text[]) AS artists,
  sc.distance AS distance,
  (1.0 - sc.distance)::int AS similarity
FROM scored sc
LEFT JOIN LATERAL (
  SELECT array_agg(sub.name) AS artists
  FROM (
    SELECT a.name
    FROM user_artists ua
    JOIN artists a ON a.id = ua.artist_id
    WHERE ua.user_id = sc.id
    ORDER BY ua.rank
    LIMIT $1::int
  ) sub
) al ON TRUE
ORDER BY
  sc.distance ASC,
  (sc.program = (SELECT target_program FROM target)) DESC,
  (sc.graduation_year = (SELECT target_grad FROM target)) DESC
`

type FindSimilarUsersParams struct {
	TopK     int32   `json:"top_k"`
	Username string  `json:"username"`
	Alpha    float64 `json:"alpha"`
	Lim      int32   `json:"lim"`
}

type FindSimilarUsersRow struct {
	Username       string      `json:"username"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Program        pgtype.Text `json:"program"`
	GraduationYear pgtype.Int4 `json:"graduation_year"`
	Artists        interface{} `json:"artists"`
	Distance       float64     `json:"distance"`
	Similarity     int32       `json:"similarity"`
}

// =======================
// Nearest neighbors (Chamfer-based)
// Replace old PWO query with Chamfer under the same exported name
// =======================
// :username => the anchor profile
// :limit_n  => how many matches to return
// Performance optimizations:
// 1) Restrict candidates to users who share at least 1 artist with the target (uses idx_user_artists_artist_user)
// 2) Compute distances first and LIMIT to top-N before fetching per-user artist arrays
// 3) Limit returned artist list to top_k via a lateral subquery to reduce memory/CPU
func (q *Queries) FindSimilarUsers(ctx context.Context, arg FindSimilarUsersParams) ([]FindSimilarUsersRow, error) {
	rows, err := q.db.Query(ctx, findSimilarUsers,
		arg.TopK,
		arg.Username,
		arg.Alpha,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarUsersRow{}
	for rows.Next() {
		var i FindSimilarUsersRow
		if err := rows.Scan(
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Program,
			&i.GraduationYear,
			&i.Artists,
			&i.Distance,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllArtists = `-- name: GetAllArtists :many
SELECT id, name, created_at, musicbrainz_id, sort_name, artist_type, gender, country, life_span_begin, life_span_end, disambiguation, musicbrainz_score, is_reference FROM artists ORDER BY name
`

func (q *Queries) GetAllArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MusicbrainzID,
			&i.SortName,
			&i.ArtistType,
			&i.Gender,
			&i.Country,
			&i.LifeSpanBegin,
			&i.LifeSpanEnd,
			&i.Disambiguation,
			&i.MusicbrainzScore,
			&i.IsReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFeedback = `-- name: GetAllFeedback :many
SELECT f.id, f.user_id, f.feedback_text, f.created_at, f.updated_at, u.username, u.first_name, u.last_name
FROM feedback f
JOIN users u ON f.user_id = u.id
ORDER BY f.created_at DESC
LIMIT $1
`

type GetAllFeedbackRow struct {
	ID           int32              `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	FeedbackText string             `json:"feedback_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
}

func (q *Queries) GetAllFeedback(ctx context.Context, lim int32) ([]GetAllFeedbackRow, error) {
	rows, err := q.db.Query(ctx, getAllFeedback, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllFeedbackRow{}
	for rows.Next() {
		var i GetAllFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedbackText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users ORDER BY created_at
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Program,
			&i.GraduationYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, created_at, musicbrainz_id, sort_name, artist_type, gender, country, life_span_begin, life_span_end, disambiguation, musicbrainz_score, is_reference FROM artists WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtistByID(ctx context.Context, id int32) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.MusicbrainzID,
		&i.SortName,
		&i.ArtistType,
		&i.Gender,
		&i.Country,
		&i.LifeSpanBegin,
		&i.LifeSpanEnd,
		&i.Disambiguation,
		&i.MusicbrainzScore,
		&i.IsReference,
	)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, created_at, musicbrainz_id, sort_name, artist_type, gender, country, life_span_begin, life_span_end, disambiguation, musicbrainz_score, is_reference FROM artists WHERE name = $1 LIMIT 1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.MusicbrainzID,
		&i.SortName,
		&i.ArtistType,
		&i.Gender,
		&i.Country,
		&i.LifeSpanBegin,
		&i.LifeSpanEnd,
		&i.Disambiguation,
		&i.MusicbrainzScore,
		&i.IsReference,
	)
	return i, err
}

const getArtistUsers = `-- name: GetArtistUsers :many
SELECT u.id, u.username, u.email, u.first_name, u.last_name, u.created_at, u.updated_at
FROM users u
JOIN user_artists ua ON u.id = ua.user_id
WHERE ua.artist_id = $1
ORDER BY u.username
`

type GetArtistUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetArtistUsers(ctx context.Context, artistID int32) ([]GetArtistUsersRow, error) {
	rows, err := q.db.Query(ctx, getArtistUsers, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArtistUsersRow{}
	for rows.Next() {
		var i GetArtistUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChicagoEventsCountWithArtistSearch = `-- name: GetChicagoEventsCountWithArtistSearch :one
SELECT COUNT(DISTINCT ce.id)
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= CURRENT_TIMESTAMP
  AND v.city ILIKE '%Chicago%'
  AND ce.status = 'onsale'
  AND ($1 = '' OR ca.name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR ucei.interest_status = $2 OR ucei.interest_status IS NULL)
`

type GetChicagoEventsCountWithArtistSearchParams struct {
	ArtistName     interface{} `json:"artist_name"`
	InterestStatus interface{} `json:"interest_status"`
}

func (q *Queries) GetChicagoEventsCountWithArtistSearch(ctx context.Context, arg GetChicagoEventsCountWithArtistSearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, getChicagoEventsCountWithArtistSearch, arg.ArtistName, arg.InterestStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChicagoEventsWithArtistSearch = `-- name: GetChicagoEventsWithArtistSearch :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
  COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id', ca.id, 'name', ca.name, 'genres', ca.genres)) FILTER (WHERE ca.id IS NOT NULL), '[]'::jsonb) AS artists_json,
  (array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL))::text[] AS interested_user_ids,
  (array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL))::text[] AS going_user_ids,
  (array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL))::text[] AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
 LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= CURRENT_TIMESTAMP
  AND v.city ILIKE '%Chicago%'
  AND ce.status = 'onsale'
  AND ($1 = '' OR ca.name ILIKE '%' || $1 || '%')
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $3 OFFSET $2
`

type GetChicagoEventsWithArtistSearchParams struct {
	ArtistName  interface{} `json:"artist_name"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type GetChicagoEventsWithArtistSearchRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistsJson            interface{}      `json:"artists_json"`
	InterestedUserIds      []string         `json:"interested_user_ids"`
	GoingUserIds           []string         `json:"going_user_ids"`
	LookingForGroupUserIds []string         `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetChicagoEventsWithArtistSearch(ctx context.Context, arg GetChicagoEventsWithArtistSearchParams) ([]GetChicagoEventsWithArtistSearchRow, error) {
	rows, err := q.db.Query(ctx, getChicagoEventsWithArtistSearch, arg.ArtistName, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChicagoEventsWithArtistSearchRow{}
	for rows.Next() {
		var i GetChicagoEventsWithArtistSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistsJson,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConcertEventByID = `-- name: GetConcertEventByID :one
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street, 
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
WHERE ce.id = $1
`

type GetConcertEventByIDRow struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	EventDate      pgtype.Timestamp `json:"event_date"`
	VenueID        pgtype.Text      `json:"venue_id"`
	Genres         []string         `json:"genres"`
	PriceMin       pgtype.Numeric   `json:"price_min"`
	PriceMax       pgtype.Numeric   `json:"price_max"`
	PriceCurrency  pgtype.Text      `json:"price_currency"`
	TicketUrl      pgtype.Text      `json:"ticket_url"`
	Description    pgtype.Text      `json:"description"`
	Status         string           `json:"status"`
	AgeRestriction pgtype.Text      `json:"age_restriction"`
	Provider       string           `json:"provider"`
	ExternalUrl    pgtype.Text      `json:"external_url"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	VenueName      pgtype.Text      `json:"venue_name"`
	VenueStreet    pgtype.Text      `json:"venue_street"`
	VenueCity      pgtype.Text      `json:"venue_city"`
	VenueState     pgtype.Text      `json:"venue_state"`
	VenueCountry   pgtype.Text      `json:"venue_country"`
	VenuePostal    pgtype.Text      `json:"venue_postal"`
	VenueCapacity  pgtype.Int4      `json:"venue_capacity"`
}

func (q *Queries) GetConcertEventByID(ctx context.Context, id string) (GetConcertEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getConcertEventByID, id)
	var i GetConcertEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.VenueID,
		&i.Genres,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceCurrency,
		&i.TicketUrl,
		&i.Description,
		&i.Status,
		&i.AgeRestriction,
		&i.Provider,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VenueName,
		&i.VenueStreet,
		&i.VenueCity,
		&i.VenueState,
		&i.VenueCountry,
		&i.VenuePostal,
		&i.VenueCapacity,
	)
	return i, err
}

const getConcertEventCount = `-- name: GetConcertEventCount :one
SELECT COUNT(DISTINCT ce.id)
FROM concert_events ce
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ($1 = '' OR ucei.interest_status = $1 OR ucei.interest_status IS NULL)
`

// Optional interest_status filter: if provided (non-empty), counts events having at least one user with that status
func (q *Queries) GetConcertEventCount(ctx context.Context, interestStatus interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, getConcertEventCount, interestStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConcertEventsInDateRange = `-- name: GetConcertEventsInDateRange :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
    /* Aggregated artist names */
    array_remove(array_agg(DISTINCT ca.name), NULL) AS artist_names,
    /* User interest buckets */
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= $1
  AND ce.event_date <= $2
  AND ($3::text IS NULL OR v.city ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR ce.status = $4)
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $6 OFFSET $5
`

type GetConcertEventsInDateRangeParams struct {
	StartDate pgtype.Timestamp `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
	City      string           `json:"city"`
	Status    string           `json:"status"`
	OffSet    int32            `json:"off_set"`
	Lim       int32            `json:"lim"`
}

type GetConcertEventsInDateRangeRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistNames            interface{}      `json:"artist_names"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetConcertEventsInDateRange(ctx context.Context, arg GetConcertEventsInDateRangeParams) ([]GetConcertEventsInDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getConcertEventsInDateRange,
		arg.StartDate,
		arg.EndDate,
		arg.City,
		arg.Status,
		arg.OffSet,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConcertEventsInDateRangeRow{}
	for rows.Next() {
		var i GetConcertEventsInDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistNames,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConcertEventsInDateRangeWithInterest = `-- name: GetConcertEventsInDateRangeWithInterest :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
    array_remove(array_agg(DISTINCT ca.name), NULL) AS artist_names,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= $1
  AND ce.event_date <= $2
  AND ($3::text IS NULL OR v.city ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR ce.status = $4)
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $6 OFFSET $5
`

type GetConcertEventsInDateRangeWithInterestParams struct {
	StartDate pgtype.Timestamp `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
	City      string           `json:"city"`
	Status    string           `json:"status"`
	OffSet    int32            `json:"off_set"`
	Lim       int32            `json:"lim"`
}

type GetConcertEventsInDateRangeWithInterestRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistNames            interface{}      `json:"artist_names"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

// Returns events within date range plus associated venue, artists, and user interest buckets
func (q *Queries) GetConcertEventsInDateRangeWithInterest(ctx context.Context, arg GetConcertEventsInDateRangeWithInterestParams) ([]GetConcertEventsInDateRangeWithInterestRow, error) {
	rows, err := q.db.Query(ctx, getConcertEventsInDateRangeWithInterest,
		arg.StartDate,
		arg.EndDate,
		arg.City,
		arg.Status,
		arg.OffSet,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConcertEventsInDateRangeWithInterestRow{}
	for rows.Next() {
		var i GetConcertEventsInDateRangeWithInterestRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistNames,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventArtists = `-- name: GetEventArtists :many
SELECT 
    ca.id,
    ca.name,
    ca.genres,
  cea.role,
  /* How many users have any interest in this event (all statuses) */
  (SELECT COUNT(DISTINCT ui.user_id) FROM user_concert_event_interest ui WHERE ui.event_id = cea.event_id) AS interested_user_count
FROM concert_artists ca
JOIN concert_event_artists cea ON ca.id = cea.artist_id
WHERE cea.event_id = $1
`

type GetEventArtistsRow struct {
	ID                  string      `json:"id"`
	Name                string      `json:"name"`
	Genres              []string    `json:"genres"`
	Role                pgtype.Text `json:"role"`
	InterestedUserCount int64       `json:"interested_user_count"`
}

func (q *Queries) GetEventArtists(ctx context.Context, eventID string) ([]GetEventArtistsRow, error) {
	rows, err := q.db.Query(ctx, getEventArtists, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventArtistsRow{}
	for rows.Next() {
		var i GetEventArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genres,
			&i.Role,
			&i.InterestedUserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForArtist = `-- name: GetEventsForArtist :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
    ca.name as artist_name,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
JOIN concert_event_artists cea ON ce.id = cea.event_id
JOIN concert_artists ca ON cea.artist_id = ca.id
 LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ca.name ILIKE '%' || $1 || '%'
  AND ce.event_date >= CURRENT_TIMESTAMP
  AND ($2::text IS NULL OR v.city ILIKE '%' || $2 || '%')
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity, ca.name
ORDER BY ce.event_date ASC
LIMIT $3
`

type GetEventsForArtistParams struct {
	ArtistName pgtype.Text `json:"artist_name"`
	City       string      `json:"city"`
	Lim        int32       `json:"lim"`
}

type GetEventsForArtistRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistName             string           `json:"artist_name"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetEventsForArtist(ctx context.Context, arg GetEventsForArtistParams) ([]GetEventsForArtistRow, error) {
	rows, err := q.db.Query(ctx, getEventsForArtist, arg.ArtistName, arg.City, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsForArtistRow{}
	for rows.Next() {
		var i GetEventsForArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistName,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackByUser = `-- name: GetFeedbackByUser :many
SELECT id, user_id, feedback_text, created_at, updated_at FROM feedback
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFeedbackByUser(ctx context.Context, userID uuid.UUID) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, getFeedbackByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedbackText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, expires_at, used, created_at FROM password_reset_tokens 
WHERE token = $1 
  AND expires_at > NOW() 
  AND used = FALSE 
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getUpcomingConcertEventsInCity = `-- name: GetUpcomingConcertEventsInCity :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= CURRENT_TIMESTAMP
  AND v.city ILIKE '%' || $1 || '%'
  AND ce.status = 'onsale'
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $2
`

type GetUpcomingConcertEventsInCityParams struct {
	City pgtype.Text `json:"city"`
	Lim  int32       `json:"lim"`
}

type GetUpcomingConcertEventsInCityRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetUpcomingConcertEventsInCity(ctx context.Context, arg GetUpcomingConcertEventsInCityParams) ([]GetUpcomingConcertEventsInCityRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingConcertEventsInCity, arg.City, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingConcertEventsInCityRow{}
	for rows.Next() {
		var i GetUpcomingConcertEventsInCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserArtists = `-- name: GetUserArtists :many
SELECT a.id, a.name, a.created_at
FROM artists a
JOIN user_artists ua ON a.id = ua.artist_id
WHERE ua.user_id = $1
ORDER BY ua.rank
`

type GetUserArtistsRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserArtists(ctx context.Context, userID uuid.UUID) ([]GetUserArtistsRow, error) {
	rows, err := q.db.Query(ctx, getUserArtists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserArtistsRow{}
	for rows.Next() {
		var i GetUserArtistsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const getUserByUsernameWithPassword = `-- name: GetUserByUsernameWithPassword :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsernameWithPassword(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameWithPassword, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const getUsersWithArtists = `-- name: GetUsersWithArtists :many

SELECT 
    u.id, u.username, u.email, u.first_name, u.last_name,
    COALESCE(array_agg(a.name) FILTER (WHERE a.name IS NOT NULL), '{}') as artist_names
FROM users u
LEFT JOIN user_artists ua ON u.id = ua.user_id
LEFT JOIN artists a ON ua.artist_id = a.id
GROUP BY u.id, u.username, u.email, u.first_name, u.last_name
ORDER BY u.username
`

type GetUsersWithArtistsRow struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	ArtistNames interface{} `json:"artist_names"`
}

// =======================
// Matching helpers / reports
// =======================
func (q *Queries) GetUsersWithArtists(ctx context.Context) ([]GetUsersWithArtistsRow, error) {
	rows, err := q.db.Query(ctx, getUsersWithArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithArtistsRow{}
	for rows.Next() {
		var i GetUsersWithArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ArtistNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetTokenAsUsed = `-- name: MarkPasswordResetTokenAsUsed :exec
UPDATE password_reset_tokens 
SET used = TRUE 
WHERE token = $1
`

func (q *Queries) MarkPasswordResetTokenAsUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenAsUsed, token)
	return err
}

const pairwiseArtistSimilarityByIDs = `-- name: PairwiseArtistSimilarityByIDs :one
SELECT 1.0 - artist_distance($1::int, $2::int) AS similarity
`

type PairwiseArtistSimilarityByIDsParams struct {
	Artist1ID int32 `json:"artist1_id"`
	Artist2ID int32 `json:"artist2_id"`
}

func (q *Queries) PairwiseArtistSimilarityByIDs(ctx context.Context, arg PairwiseArtistSimilarityByIDsParams) (int32, error) {
	row := q.db.QueryRow(ctx, pairwiseArtistSimilarityByIDs, arg.Artist1ID, arg.Artist2ID)
	var similarity int32
	err := row.Scan(&similarity)
	return similarity, err
}

const pairwiseArtistSimilarityByNames = `-- name: PairwiseArtistSimilarityByNames :one

SELECT
  a1.name AS name1,
  a2.name AS name2,
  1.0 - artist_distance(a1.id, a2.id) AS similarity
FROM artists a1
JOIN artists a2 ON TRUE
WHERE a1.name = $1
  AND a2.name = $2
`

type PairwiseArtistSimilarityByNamesParams struct {
	Name1 string `json:"name1"`
	Name2 string `json:"name2"`
}

type PairwiseArtistSimilarityByNamesRow struct {
	Name1      string `json:"name1"`
	Name2      string `json:"name2"`
	Similarity int32  `json:"similarity"`
}

// =======================
// New similarity APIs (artist + set)
// =======================
func (q *Queries) PairwiseArtistSimilarityByNames(ctx context.Context, arg PairwiseArtistSimilarityByNamesParams) (PairwiseArtistSimilarityByNamesRow, error) {
	row := q.db.QueryRow(ctx, pairwiseArtistSimilarityByNames, arg.Name1, arg.Name2)
	var i PairwiseArtistSimilarityByNamesRow
	err := row.Scan(&i.Name1, &i.Name2, &i.Similarity)
	return i, err
}

const removeUserArtist = `-- name: RemoveUserArtist :exec
DELETE FROM user_artists WHERE user_id = $1 AND artist_id = $2
`

type RemoveUserArtistParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ArtistID int32     `json:"artist_id"`
}

func (q *Queries) RemoveUserArtist(ctx context.Context, arg RemoveUserArtistParams) error {
	_, err := q.db.Exec(ctx, removeUserArtist, arg.UserID, arg.ArtistID)
	return err
}

const searchArtists = `-- name: SearchArtists :many
SELECT id, name, created_at, musicbrainz_id, sort_name, artist_type, gender, country, life_span_begin, life_span_end, disambiguation, musicbrainz_score, is_reference FROM artists 
WHERE LOWER(name) LIKE LOWER($1) 
ORDER BY 
  CASE 
    WHEN LOWER(name) = LOWER($2) THEN 1
    WHEN LOWER(name) LIKE LOWER($3) THEN 2
    ELSE 3
  END,
  LENGTH(name),
  name
LIMIT $4
`

type SearchArtistsParams struct {
	SearchTerm   string `json:"search_term"`
	ExactMatch   string `json:"exact_match"`
	PartialMatch string `json:"partial_match"`
	Lim          int32  `json:"lim"`
}

func (q *Queries) SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, searchArtists,
		arg.SearchTerm,
		arg.ExactMatch,
		arg.PartialMatch,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MusicbrainzID,
			&i.SortName,
			&i.ArtistType,
			&i.Gender,
			&i.Country,
			&i.LifeSpanBegin,
			&i.LifeSpanEnd,
			&i.Disambiguation,
			&i.MusicbrainzScore,
			&i.IsReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserArtists = `-- name: SetUserArtists :exec
WITH new_artists AS (
  INSERT INTO artists (name)
  SELECT unnest($2::text[])
  ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
  RETURNING id, name
),
 ranked_artists AS (
  SELECT 
    a.id,
    a.name,
    ($3::int[])[array_position($2::text[], a.name)] as rank
  FROM new_artists a
)
INSERT INTO user_artists (user_id, artist_id, rank)
SELECT $1::uuid, id, rank FROM ranked_artists
ON CONFLICT (user_id, artist_id) DO UPDATE SET rank = EXCLUDED.rank
`

type SetUserArtistsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ArtistNames []string  `json:"artist_names"`
	Ranks       []int32   `json:"ranks"`
}

func (q *Queries) SetUserArtists(ctx context.Context, arg SetUserArtistsParams) error {
	_, err := q.db.Exec(ctx, setUserArtists, arg.UserID, arg.ArtistNames, arg.Ranks)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET first_name = $1, last_name = $2, email = $3
WHERE id = $4
RETURNING id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year
`

type UpdateUserParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users 
SET password_hash = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, username, email
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

type UpdateUserPasswordRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i UpdateUserPasswordRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const upsertConcertArtist = `-- name: UpsertConcertArtist :one
INSERT INTO concert_artists (id, name, genres)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    genres = EXCLUDED.genres,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, genres, created_at, updated_at
`

type UpsertConcertArtistParams struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Genres []string `json:"genres"`
}

func (q *Queries) UpsertConcertArtist(ctx context.Context, arg UpsertConcertArtistParams) (ConcertArtist, error) {
	row := q.db.QueryRow(ctx, upsertConcertArtist, arg.ID, arg.Name, arg.Genres)
	var i ConcertArtist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConcertEvent = `-- name: UpsertConcertEvent :one
INSERT INTO concert_events (id, name, event_date, venue_id, genres, price_min, price_max, price_currency, ticket_url, description, status, age_restriction, provider, external_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    event_date = EXCLUDED.event_date,
    venue_id = EXCLUDED.venue_id,
    genres = EXCLUDED.genres,
    price_min = EXCLUDED.price_min,
    price_max = EXCLUDED.price_max,
    price_currency = EXCLUDED.price_currency,
    ticket_url = EXCLUDED.ticket_url,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    age_restriction = EXCLUDED.age_restriction,
    provider = EXCLUDED.provider,
    external_url = EXCLUDED.external_url,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, event_date, venue_id, genres, price_min, price_max, price_currency, ticket_url, description, status, age_restriction, provider, external_url, created_at, updated_at
`

type UpsertConcertEventParams struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	EventDate      pgtype.Timestamp `json:"event_date"`
	VenueID        pgtype.Text      `json:"venue_id"`
	Genres         []string         `json:"genres"`
	PriceMin       pgtype.Numeric   `json:"price_min"`
	PriceMax       pgtype.Numeric   `json:"price_max"`
	PriceCurrency  pgtype.Text      `json:"price_currency"`
	TicketUrl      pgtype.Text      `json:"ticket_url"`
	Description    pgtype.Text      `json:"description"`
	Status         string           `json:"status"`
	AgeRestriction pgtype.Text      `json:"age_restriction"`
	Provider       string           `json:"provider"`
	ExternalUrl    pgtype.Text      `json:"external_url"`
}

func (q *Queries) UpsertConcertEvent(ctx context.Context, arg UpsertConcertEventParams) (ConcertEvent, error) {
	row := q.db.QueryRow(ctx, upsertConcertEvent,
		arg.ID,
		arg.Name,
		arg.EventDate,
		arg.VenueID,
		arg.Genres,
		arg.PriceMin,
		arg.PriceMax,
		arg.PriceCurrency,
		arg.TicketUrl,
		arg.Description,
		arg.Status,
		arg.AgeRestriction,
		arg.Provider,
		arg.ExternalUrl,
	)
	var i ConcertEvent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.VenueID,
		&i.Genres,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceCurrency,
		&i.TicketUrl,
		&i.Description,
		&i.Status,
		&i.AgeRestriction,
		&i.Provider,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventArtist = `-- name: UpsertEventArtist :exec
INSERT INTO concert_event_artists (event_id, artist_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, artist_id) DO UPDATE SET
    role = EXCLUDED.role
`

type UpsertEventArtistParams struct {
	EventID  string      `json:"event_id"`
	ArtistID string      `json:"artist_id"`
	Role     pgtype.Text `json:"role"`
}

func (q *Queries) UpsertEventArtist(ctx context.Context, arg UpsertEventArtistParams) error {
	_, err := q.db.Exec(ctx, upsertEventArtist, arg.EventID, arg.ArtistID, arg.Role)
	return err
}

const upsertUserConcertEventInterest = `-- name: UpsertUserConcertEventInterest :exec
INSERT INTO user_concert_event_interest (user_id, event_id, interest_status)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, event_id)
DO UPDATE SET interest_status = EXCLUDED.interest_status, updated_at = NOW()
`

type UpsertUserConcertEventInterestParams struct {
	UserID         uuid.UUID `json:"user_id"`
	EventID        string    `json:"event_id"`
	InterestStatus string    `json:"interest_status"`
}

func (q *Queries) UpsertUserConcertEventInterest(ctx context.Context, arg UpsertUserConcertEventInterestParams) error {
	_, err := q.db.Exec(ctx, upsertUserConcertEventInterest, arg.UserID, arg.EventID, arg.InterestStatus)
	return err
}

const upsertVenue = `-- name: UpsertVenue :one

INSERT INTO venues (id, name, street, city, state, country, postal, capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    street = EXCLUDED.street,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    country = EXCLUDED.country,
    postal = EXCLUDED.postal,
    capacity = EXCLUDED.capacity,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, street, city, state, country, postal, capacity, created_at, updated_at
`

type UpsertVenueParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Street   pgtype.Text `json:"street"`
	City     string      `json:"city"`
	State    pgtype.Text `json:"state"`
	Country  string      `json:"country"`
	Postal   pgtype.Text `json:"postal"`
	Capacity pgtype.Int4 `json:"capacity"`
}

// =======================
// Concert Events
// =======================
func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, upsertVenue,
		arg.ID,
		arg.Name,
		arg.Street,
		arg.City,
		arg.State,
		arg.Country,
		arg.Postal,
		arg.Capacity,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.State,
		&i.Country,
		&i.Postal,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userChamferSimilarity = `-- name: UserChamferSimilarity :one
SELECT user_chamfer_similarity(
  $1::uuid,
  $2::uuid,
  $3::int,
  $4::float8
) AS similarity
`

type UserChamferSimilarityParams struct {
	User1ID uuid.UUID `json:"user1_id"`
	User2ID uuid.UUID `json:"user2_id"`
	TopK    int32     `json:"top_k"`
	Alpha   float64   `json:"alpha"`
}

func (q *Queries) UserChamferSimilarity(ctx context.Context, arg UserChamferSimilarityParams) (float64, error) {
	row := q.db.QueryRow(ctx, userChamferSimilarity,
		arg.User1ID,
		arg.User2ID,
		arg.TopK,
		arg.Alpha,
	)
	var similarity float64
	err := row.Scan(&similarity)
	return similarity, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
