// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedback = `-- name: CreateFeedback :one

INSERT INTO feedback (user_id, feedback_text)
VALUES ($1, $2)
RETURNING id, user_id, feedback_text, created_at, updated_at
`

type CreateFeedbackParams struct {
	UserID       uuid.UUID `json:"user_id"`
	FeedbackText string    `json:"feedback_text"`
}

// (If you also want the :by-user-id variant, keep your FindSimilarUsersChamferByUserID below unchanged.)
// Feedback queries
func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback, arg.UserID, arg.FeedbackText)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedbackText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, used, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// =======================
// Password Reset Tokens
// =======================
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, email, first_name, last_name, password_hash, program, graduation_year)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year
`

type CreateUserParams struct {
	ID             uuid.UUID   `json:"id"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	PasswordHash   string      `json:"password_hash"`
	Program        pgtype.Text `json:"program"`
	GraduationYear pgtype.Int4 `json:"graduation_year"`
}

// =======================
// Users
// =======================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.Program,
		arg.GraduationYear,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens 
WHERE expires_at < NOW() - INTERVAL '1 hour'
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteOldConcertEvents = `-- name: DeleteOldConcertEvents :exec
DELETE FROM concert_events 
WHERE event_date < $1
`

func (q *Queries) DeleteOldConcertEvents(ctx context.Context, cutoffDate pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteOldConcertEvents, cutoffDate)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const deleteSpotifyTopArtistSnapshotForRange = `-- name: DeleteSpotifyTopArtistSnapshotForRange :exec
DELETE FROM spotify_top_artist_snapshots 
WHERE user_id = $1 AND range = $2 AND fetched_at < $3
`

type DeleteSpotifyTopArtistSnapshotForRangeParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	Range           string             `json:"range"`
	FetchedAtCutoff pgtype.Timestamptz `json:"fetched_at_cutoff"`
}

func (q *Queries) DeleteSpotifyTopArtistSnapshotForRange(ctx context.Context, arg DeleteSpotifyTopArtistSnapshotForRangeParams) error {
	_, err := q.db.Exec(ctx, deleteSpotifyTopArtistSnapshotForRange, arg.UserID, arg.Range, arg.FetchedAtCutoff)
	return err
}

const deleteSpotifyTopTrackSnapshotForRange = `-- name: DeleteSpotifyTopTrackSnapshotForRange :exec
DELETE FROM spotify_top_track_snapshots 
WHERE user_id = $1 AND range = $2 AND fetched_at < $3
`

type DeleteSpotifyTopTrackSnapshotForRangeParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	Range           string             `json:"range"`
	FetchedAtCutoff pgtype.Timestamptz `json:"fetched_at_cutoff"`
}

func (q *Queries) DeleteSpotifyTopTrackSnapshotForRange(ctx context.Context, arg DeleteSpotifyTopTrackSnapshotForRangeParams) error {
	_, err := q.db.Exec(ctx, deleteSpotifyTopTrackSnapshotForRange, arg.UserID, arg.Range, arg.FetchedAtCutoff)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserConcertEventInterest = `-- name: DeleteUserConcertEventInterest :exec
DELETE FROM user_concert_event_interest
WHERE user_id = $1 AND event_id = $2
`

type DeleteUserConcertEventInterestParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EventID string    `json:"event_id"`
}

func (q *Queries) DeleteUserConcertEventInterest(ctx context.Context, arg DeleteUserConcertEventInterestParams) error {
	_, err := q.db.Exec(ctx, deleteUserConcertEventInterest, arg.UserID, arg.EventID)
	return err
}

const deleteUserPasswordResetTokens = `-- name: DeleteUserPasswordResetTokens :exec
DELETE FROM password_reset_tokens 
WHERE user_id = $1
`

func (q *Queries) DeleteUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPasswordResetTokens, userID)
	return err
}

const findTopNSimilarUsersBySpotifyArtists = `-- name: FindTopNSimilarUsersBySpotifyArtists :many

WITH anchor AS (
  SELECT v.user_id AS anchor_user_id, v.item_rank AS anchor_item_rank, v.spotify_artist_id, v.name AS anchor_name
  FROM v_current_spotify_top_artists v
  WHERE v.user_id = $2 AND v.range = $3 AND v.item_rank <= $4
), others AS (
  SELECT v.user_id AS other_user_id, v.item_rank AS other_item_rank, v.spotify_artist_id, v.name AS other_name
  FROM v_current_spotify_top_artists v
  WHERE v.user_id <> $2 AND v.range = $3 AND v.item_rank <= $4
), overlap AS (
  SELECT o.other_user_id,
         a.spotify_artist_id,
         a.anchor_name AS name,
         a.anchor_item_rank AS anchor_rank,
         o.other_item_rank AS other_rank,
         1.0 / (a.anchor_item_rank + o.other_item_rank)::float8 AS weight
  FROM anchor a
  JOIN others o USING (spotify_artist_id)
), agg AS (
  SELECT other_user_id,
    SUM(weight)::float8 AS similarity,
       jsonb_agg(jsonb_build_object(
         'spotify_artist_id', spotify_artist_id,
         'name', name,
         'anchor_rank', anchor_rank,
         'other_rank', other_rank
       ) ORDER BY (anchor_rank + other_rank), anchor_rank, other_rank) AS overlaps_json
  FROM overlap
  GROUP BY other_user_id

)
SELECT u.id AS user_id,
  u.username,
  u.first_name,
  u.last_name,
  u.program,
  u.graduation_year,
  agg.similarity,
  agg.overlaps_json
FROM agg
JOIN users u ON u.id = agg.other_user_id
WHERE agg.similarity > 0
ORDER BY agg.similarity DESC, u.created_at ASC
LIMIT $1
`

type FindTopNSimilarUsersBySpotifyArtistsParams struct {
	LimitN       int32     `json:"limit_n"`
	AnchorUserID uuid.UUID `json:"anchor_user_id"`
	Range        string    `json:"range"`
	TopN         int32     `json:"top_n"`
}

type FindTopNSimilarUsersBySpotifyArtistsRow struct {
	UserID         uuid.UUID   `json:"user_id"`
	Username       string      `json:"username"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Program        pgtype.Text `json:"program"`
	GraduationYear pgtype.Int4 `json:"graduation_year"`
	Similarity     float64     `json:"similarity"`
	OverlapsJson   []byte      `json:"overlaps_json"`
}

// =======================
// Spotify Top Items
// =======================
// Given an anchor user (user_id) and a Spotify time range, compute similarity to other users
// based on overlapping top artists in the latest snapshot for that range per user.
// Similarity uses a rank-weighted reciprocal scheme: weight = 1 / (r_anchor + r_other)
// and aggregated similarity = SUM(weights) over all overlapping artist_ids.
// Returns top N other users ordered by descending similarity. Ties resolved by created_at asc.
// Also returns the overlapping artist names and their anchor/other ranks encoded as JSON.
// Parameters:
//
//	user_id UUID          -> anchor user
//	range   TEXT          -> spotify range ('short_term'|'medium_term'|'long_term')
//	limit_n INT           -> maximum similar users to return
//	top_n   INT           -> consider only top N ranked items per user
//
// Notes:
//   - We restrict snapshots to only the most recent fetched_at per user per range using the views.
//   - We filter out users with zero overlap.
//   - JSON structure for overlaps: [{"spotify_artist_id":"...","name":"...","anchor_rank":1,"other_rank":2}]
func (q *Queries) FindTopNSimilarUsersBySpotifyArtists(ctx context.Context, arg FindTopNSimilarUsersBySpotifyArtistsParams) ([]FindTopNSimilarUsersBySpotifyArtistsRow, error) {
	rows, err := q.db.Query(ctx, findTopNSimilarUsersBySpotifyArtists,
		arg.LimitN,
		arg.AnchorUserID,
		arg.Range,
		arg.TopN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTopNSimilarUsersBySpotifyArtistsRow{}
	for rows.Next() {
		var i FindTopNSimilarUsersBySpotifyArtistsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Program,
			&i.GraduationYear,
			&i.Similarity,
			&i.OverlapsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTopNSimilarUsersBySpotifyTracks = `-- name: FindTopNSimilarUsersBySpotifyTracks :many
WITH anchor AS (
  SELECT v.user_id AS anchor_user_id, v.item_rank AS anchor_item_rank, v.spotify_track_id, v.name AS anchor_name
  FROM v_current_spotify_top_tracks v
  WHERE v.user_id = $2 AND v.range = $3 AND v.item_rank <= $4
), others AS (
  SELECT v.user_id AS other_user_id, v.item_rank AS other_item_rank, v.spotify_track_id, v.name AS other_name
  FROM v_current_spotify_top_tracks v
  WHERE v.user_id <> $2 AND v.range = $3 AND v.item_rank <= $4
), overlap AS (
  SELECT o.other_user_id,
         a.spotify_track_id,
         a.anchor_name AS name,
         a.anchor_item_rank AS anchor_rank,
         o.other_item_rank AS other_rank,
         1.0 / (a.anchor_item_rank + o.other_item_rank)::float8 AS weight
  FROM anchor a
  JOIN others o USING (spotify_track_id)
), agg AS (
  SELECT other_user_id,
    SUM(weight)::float8 AS similarity,
       jsonb_agg(jsonb_build_object(
         'spotify_track_id', spotify_track_id,
         'name', name,
         'anchor_rank', anchor_rank,
         'other_rank', other_rank
       ) ORDER BY (anchor_rank + other_rank), anchor_rank, other_rank) AS overlaps_json
  FROM overlap
  GROUP BY other_user_id
)
SELECT u.id AS user_id,
     u.username,
     u.first_name,
     u.last_name,
     u.program,
     u.graduation_year,
     agg.similarity,
     agg.overlaps_json
FROM agg
JOIN users u ON u.id = agg.other_user_id
WHERE agg.similarity > 0
ORDER BY agg.similarity DESC, u.created_at ASC
LIMIT $1
`

type FindTopNSimilarUsersBySpotifyTracksParams struct {
	LimitN       int32     `json:"limit_n"`
	AnchorUserID uuid.UUID `json:"anchor_user_id"`
	Range        string    `json:"range"`
	TopN         int32     `json:"top_n"`
}

type FindTopNSimilarUsersBySpotifyTracksRow struct {
	UserID         uuid.UUID   `json:"user_id"`
	Username       string      `json:"username"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Program        pgtype.Text `json:"program"`
	GraduationYear pgtype.Int4 `json:"graduation_year"`
	Similarity     float64     `json:"similarity"`
	OverlapsJson   []byte      `json:"overlaps_json"`
}

// Similar to artist similarity but operates on track snapshots.
func (q *Queries) FindTopNSimilarUsersBySpotifyTracks(ctx context.Context, arg FindTopNSimilarUsersBySpotifyTracksParams) ([]FindTopNSimilarUsersBySpotifyTracksRow, error) {
	rows, err := q.db.Query(ctx, findTopNSimilarUsersBySpotifyTracks,
		arg.LimitN,
		arg.AnchorUserID,
		arg.Range,
		arg.TopN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTopNSimilarUsersBySpotifyTracksRow{}
	for rows.Next() {
		var i FindTopNSimilarUsersBySpotifyTracksRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Program,
			&i.GraduationYear,
			&i.Similarity,
			&i.OverlapsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFeedback = `-- name: GetAllFeedback :many
SELECT f.id, f.user_id, f.feedback_text, f.created_at, f.updated_at, u.username, u.first_name, u.last_name
FROM feedback f
JOIN users u ON f.user_id = u.id
ORDER BY f.created_at DESC
LIMIT $1
`

type GetAllFeedbackRow struct {
	ID           int32              `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	FeedbackText string             `json:"feedback_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
}

func (q *Queries) GetAllFeedback(ctx context.Context, lim int32) ([]GetAllFeedbackRow, error) {
	rows, err := q.db.Query(ctx, getAllFeedback, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllFeedbackRow{}
	for rows.Next() {
		var i GetAllFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedbackText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users ORDER BY created_at
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Program,
			&i.GraduationYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnyPushSubscriptions = `-- name: GetAnyPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, updated_at, last_used_at FROM push_subscriptions ORDER BY updated_at DESC LIMIT $1
`

func (q *Queries) GetAnyPushSubscriptions(ctx context.Context, lim int32) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, getAnyPushSubscriptions, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChicagoEventsCountWithArtistSearch = `-- name: GetChicagoEventsCountWithArtistSearch :one
SELECT COUNT(DISTINCT ce.id)
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= CURRENT_TIMESTAMP
  AND v.city ILIKE '%Chicago%'
  AND ce.status = 'onsale'
  AND ($1 = '' OR ca.name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR ucei.interest_status = $2 OR ucei.interest_status IS NULL)
  AND ($3::bool = false OR EXISTS (SELECT 1 FROM user_concert_event_interest u2 WHERE u2.event_id = ce.id))
  AND (
    $4::bool = false OR EXISTS (
      SELECT 1
      FROM v_current_spotify_top_artists sta
      WHERE sta.user_id = $5
        AND sta.range = 'medium_term'
        AND sta.item_rank <= $6
        AND lower(sta.name) = lower(ca.name)
    )
  )
`

type GetChicagoEventsCountWithArtistSearchParams struct {
	ArtistName       interface{} `json:"artist_name"`
	InterestStatus   interface{} `json:"interest_status"`
	AnyInterest      bool        `json:"any_interest"`
	OnlyMyTopArtists bool        `json:"only_my_top_artists"`
	AnchorUserID     uuid.UUID   `json:"anchor_user_id"`
	TopN             int32       `json:"top_n"`
}

func (q *Queries) GetChicagoEventsCountWithArtistSearch(ctx context.Context, arg GetChicagoEventsCountWithArtistSearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, getChicagoEventsCountWithArtistSearch,
		arg.ArtistName,
		arg.InterestStatus,
		arg.AnyInterest,
		arg.OnlyMyTopArtists,
		arg.AnchorUserID,
		arg.TopN,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChicagoEventsWithArtistSearch = `-- name: GetChicagoEventsWithArtistSearch :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
  COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id', ca.id, 'name', ca.name, 'genres', ca.genres)) FILTER (WHERE ca.id IS NOT NULL), '[]'::jsonb) AS artists_json,
  (array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL))::text[] AS interested_user_ids,
  (array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL))::text[] AS going_user_ids,
  (array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL))::text[] AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
 LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= CURRENT_TIMESTAMP
  AND v.city ILIKE '%Chicago%'
  AND ce.status = 'onsale'
  AND ($1 = '' OR ca.name ILIKE '%' || $1 || '%')
  AND ($2::bool = false OR EXISTS (SELECT 1 FROM user_concert_event_interest u2 WHERE u2.event_id = ce.id))
  AND (
    $3::bool = false OR EXISTS (
      SELECT 1
      FROM v_current_spotify_top_artists sta
      WHERE sta.user_id = $4
        AND sta.range = 'medium_term'
        AND sta.item_rank <= $5
        AND lower(sta.name) = lower(ca.name)
    )
  )
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $7 OFFSET $6
`

type GetChicagoEventsWithArtistSearchParams struct {
	ArtistName       interface{} `json:"artist_name"`
	AnyInterest      bool        `json:"any_interest"`
	OnlyMyTopArtists bool        `json:"only_my_top_artists"`
	AnchorUserID     uuid.UUID   `json:"anchor_user_id"`
	TopN             int32       `json:"top_n"`
	OffsetCount      int32       `json:"offset_count"`
	LimitCount       int32       `json:"limit_count"`
}

type GetChicagoEventsWithArtistSearchRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistsJson            interface{}      `json:"artists_json"`
	InterestedUserIds      []string         `json:"interested_user_ids"`
	GoingUserIds           []string         `json:"going_user_ids"`
	LookingForGroupUserIds []string         `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetChicagoEventsWithArtistSearch(ctx context.Context, arg GetChicagoEventsWithArtistSearchParams) ([]GetChicagoEventsWithArtistSearchRow, error) {
	rows, err := q.db.Query(ctx, getChicagoEventsWithArtistSearch,
		arg.ArtistName,
		arg.AnyInterest,
		arg.OnlyMyTopArtists,
		arg.AnchorUserID,
		arg.TopN,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChicagoEventsWithArtistSearchRow{}
	for rows.Next() {
		var i GetChicagoEventsWithArtistSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistsJson,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConcertEventByID = `-- name: GetConcertEventByID :one
SELECT 
  ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
  v.name as venue_name,
  v.street as venue_street, 
  v.city as venue_city,
  v.state as venue_state,
  v.country as venue_country,
  v.postal as venue_postal,
  v.capacity as venue_capacity
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
WHERE ce.id = $1
`

type GetConcertEventByIDRow struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	EventDate      pgtype.Timestamp `json:"event_date"`
	VenueID        pgtype.Text      `json:"venue_id"`
	Genres         []string         `json:"genres"`
	PriceMin       pgtype.Numeric   `json:"price_min"`
	PriceMax       pgtype.Numeric   `json:"price_max"`
	PriceCurrency  pgtype.Text      `json:"price_currency"`
	TicketUrl      pgtype.Text      `json:"ticket_url"`
	Description    pgtype.Text      `json:"description"`
	Status         string           `json:"status"`
	AgeRestriction pgtype.Text      `json:"age_restriction"`
	Provider       string           `json:"provider"`
	ExternalUrl    pgtype.Text      `json:"external_url"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	VenueName      pgtype.Text      `json:"venue_name"`
	VenueStreet    pgtype.Text      `json:"venue_street"`
	VenueCity      pgtype.Text      `json:"venue_city"`
	VenueState     pgtype.Text      `json:"venue_state"`
	VenueCountry   pgtype.Text      `json:"venue_country"`
	VenuePostal    pgtype.Text      `json:"venue_postal"`
	VenueCapacity  pgtype.Int4      `json:"venue_capacity"`
}

func (q *Queries) GetConcertEventByID(ctx context.Context, id string) (GetConcertEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getConcertEventByID, id)
	var i GetConcertEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.VenueID,
		&i.Genres,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceCurrency,
		&i.TicketUrl,
		&i.Description,
		&i.Status,
		&i.AgeRestriction,
		&i.Provider,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VenueName,
		&i.VenueStreet,
		&i.VenueCity,
		&i.VenueState,
		&i.VenueCountry,
		&i.VenuePostal,
		&i.VenueCapacity,
	)
	return i, err
}

const getConcertEventCount = `-- name: GetConcertEventCount :one
SELECT COUNT(DISTINCT ce.id)
FROM concert_events ce
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ($1 = '' OR ucei.interest_status = $1 OR ucei.interest_status IS NULL)
`

// Optional interest_status filter: if provided (non-empty), counts events having at least one user with that status
func (q *Queries) GetConcertEventCount(ctx context.Context, interestStatus interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, getConcertEventCount, interestStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConcertEventsInDateRange = `-- name: GetConcertEventsInDateRange :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
    /* Aggregated artist names */
    array_remove(array_agg(DISTINCT ca.name), NULL) AS artist_names,
    /* User interest buckets */
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= $1
  AND ce.event_date <= $2
  AND ($3::text IS NULL OR v.city ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR ce.status = $4)
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $6 OFFSET $5
`

type GetConcertEventsInDateRangeParams struct {
	StartDate pgtype.Timestamp `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
	City      string           `json:"city"`
	Status    string           `json:"status"`
	OffSet    int32            `json:"off_set"`
	Lim       int32            `json:"lim"`
}

type GetConcertEventsInDateRangeRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistNames            interface{}      `json:"artist_names"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetConcertEventsInDateRange(ctx context.Context, arg GetConcertEventsInDateRangeParams) ([]GetConcertEventsInDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getConcertEventsInDateRange,
		arg.StartDate,
		arg.EndDate,
		arg.City,
		arg.Status,
		arg.OffSet,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConcertEventsInDateRangeRow{}
	for rows.Next() {
		var i GetConcertEventsInDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistNames,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConcertEventsInDateRangeWithInterest = `-- name: GetConcertEventsInDateRangeWithInterest :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
    array_remove(array_agg(DISTINCT ca.name), NULL) AS artist_names,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN concert_event_artists cea ON ce.id = cea.event_id
LEFT JOIN concert_artists ca ON cea.artist_id = ca.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= $1
  AND ce.event_date <= $2
  AND ($3::text IS NULL OR v.city ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR ce.status = $4)
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $6 OFFSET $5
`

type GetConcertEventsInDateRangeWithInterestParams struct {
	StartDate pgtype.Timestamp `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
	City      string           `json:"city"`
	Status    string           `json:"status"`
	OffSet    int32            `json:"off_set"`
	Lim       int32            `json:"lim"`
}

type GetConcertEventsInDateRangeWithInterestRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistNames            interface{}      `json:"artist_names"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

// Returns events within date range plus associated venue, artists, and user interest buckets
func (q *Queries) GetConcertEventsInDateRangeWithInterest(ctx context.Context, arg GetConcertEventsInDateRangeWithInterestParams) ([]GetConcertEventsInDateRangeWithInterestRow, error) {
	rows, err := q.db.Query(ctx, getConcertEventsInDateRangeWithInterest,
		arg.StartDate,
		arg.EndDate,
		arg.City,
		arg.Status,
		arg.OffSet,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConcertEventsInDateRangeWithInterestRow{}
	for rows.Next() {
		var i GetConcertEventsInDateRangeWithInterestRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistNames,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventArtists = `-- name: GetEventArtists :many
SELECT 
    ca.id,
    ca.name,
    ca.genres,
  cea.role,
  /* How many users have any interest in this event (all statuses) */
  (SELECT COUNT(DISTINCT ui.user_id) FROM user_concert_event_interest ui WHERE ui.event_id = cea.event_id) AS interested_user_count
FROM concert_artists ca
JOIN concert_event_artists cea ON ca.id = cea.artist_id
WHERE cea.event_id = $1
`

type GetEventArtistsRow struct {
	ID                  string      `json:"id"`
	Name                string      `json:"name"`
	Genres              []string    `json:"genres"`
	Role                pgtype.Text `json:"role"`
	InterestedUserCount int64       `json:"interested_user_count"`
}

func (q *Queries) GetEventArtists(ctx context.Context, eventID string) ([]GetEventArtistsRow, error) {
	rows, err := q.db.Query(ctx, getEventArtists, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventArtistsRow{}
	for rows.Next() {
		var i GetEventArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genres,
			&i.Role,
			&i.InterestedUserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForArtist = `-- name: GetEventsForArtist :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
    ca.name as artist_name,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
JOIN concert_event_artists cea ON ce.id = cea.event_id
JOIN concert_artists ca ON cea.artist_id = ca.id
 LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ca.name ILIKE '%' || $1 || '%'
  AND ce.event_date >= CURRENT_TIMESTAMP
  AND ($2::text IS NULL OR v.city ILIKE '%' || $2 || '%')
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity, ca.name
ORDER BY ce.event_date ASC
LIMIT $3
`

type GetEventsForArtistParams struct {
	ArtistName pgtype.Text `json:"artist_name"`
	City       string      `json:"city"`
	Lim        int32       `json:"lim"`
}

type GetEventsForArtistRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	ArtistName             string           `json:"artist_name"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetEventsForArtist(ctx context.Context, arg GetEventsForArtistParams) ([]GetEventsForArtistRow, error) {
	rows, err := q.db.Query(ctx, getEventsForArtist, arg.ArtistName, arg.City, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsForArtistRow{}
	for rows.Next() {
		var i GetEventsForArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.ArtistName,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackByUser = `-- name: GetFeedbackByUser :many
SELECT id, user_id, feedback_text, created_at, updated_at FROM feedback
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFeedbackByUser(ctx context.Context, userID uuid.UUID) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, getFeedbackByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedbackText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, expires_at, used, created_at FROM password_reset_tokens 
WHERE token = $1 
  AND expires_at > NOW() 
  AND used = FALSE 
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getPushSubscriptionsByUser = `-- name: GetPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, updated_at, last_used_at FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) GetPushSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, getPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotifyTokensByUser = `-- name: GetSpotifyTokensByUser :one
SELECT user_id, access_token, refresh_token_encrypted, expires_at, scope, token_type, created_at, updated_at FROM spotify_tokens WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSpotifyTokensByUser(ctx context.Context, userID uuid.UUID) (SpotifyToken, error) {
	row := q.db.QueryRow(ctx, getSpotifyTokensByUser, userID)
	var i SpotifyToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshTokenEncrypted,
		&i.ExpiresAt,
		&i.Scope,
		&i.TokenType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpcomingConcertEventsInCity = `-- name: GetUpcomingConcertEventsInCity :many
SELECT 
    ce.id, ce.name, ce.event_date, ce.venue_id, ce.genres, ce.price_min, ce.price_max, ce.price_currency, ce.ticket_url, ce.description, ce.status, ce.age_restriction, ce.provider, ce.external_url, ce.created_at, ce.updated_at,
    v.name as venue_name,
    v.street as venue_street,
    v.city as venue_city,
    v.state as venue_state,
    v.country as venue_country,
    v.postal as venue_postal,
    v.capacity as venue_capacity,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'INTERESTED'), NULL) AS interested_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'GOING'), NULL) AS going_user_ids,
  array_remove(array_agg(DISTINCT ucei.user_id::text) FILTER (WHERE ucei.interest_status = 'LOOKING_FOR_GROUP'), NULL) AS looking_for_group_user_ids
FROM concert_events ce
LEFT JOIN venues v ON ce.venue_id = v.id
LEFT JOIN user_concert_event_interest ucei ON ucei.event_id = ce.id
WHERE ce.event_date >= CURRENT_TIMESTAMP
  AND v.city ILIKE '%' || $1 || '%'
  AND ce.status = 'onsale'
GROUP BY ce.id, v.name, v.street, v.city, v.state, v.country, v.postal, v.capacity
ORDER BY ce.event_date ASC
LIMIT $2
`

type GetUpcomingConcertEventsInCityParams struct {
	City pgtype.Text `json:"city"`
	Lim  int32       `json:"lim"`
}

type GetUpcomingConcertEventsInCityRow struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	EventDate              pgtype.Timestamp `json:"event_date"`
	VenueID                pgtype.Text      `json:"venue_id"`
	Genres                 []string         `json:"genres"`
	PriceMin               pgtype.Numeric   `json:"price_min"`
	PriceMax               pgtype.Numeric   `json:"price_max"`
	PriceCurrency          pgtype.Text      `json:"price_currency"`
	TicketUrl              pgtype.Text      `json:"ticket_url"`
	Description            pgtype.Text      `json:"description"`
	Status                 string           `json:"status"`
	AgeRestriction         pgtype.Text      `json:"age_restriction"`
	Provider               string           `json:"provider"`
	ExternalUrl            pgtype.Text      `json:"external_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	VenueName              pgtype.Text      `json:"venue_name"`
	VenueStreet            pgtype.Text      `json:"venue_street"`
	VenueCity              pgtype.Text      `json:"venue_city"`
	VenueState             pgtype.Text      `json:"venue_state"`
	VenueCountry           pgtype.Text      `json:"venue_country"`
	VenuePostal            pgtype.Text      `json:"venue_postal"`
	VenueCapacity          pgtype.Int4      `json:"venue_capacity"`
	InterestedUserIds      interface{}      `json:"interested_user_ids"`
	GoingUserIds           interface{}      `json:"going_user_ids"`
	LookingForGroupUserIds interface{}      `json:"looking_for_group_user_ids"`
}

func (q *Queries) GetUpcomingConcertEventsInCity(ctx context.Context, arg GetUpcomingConcertEventsInCityParams) ([]GetUpcomingConcertEventsInCityRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingConcertEventsInCity, arg.City, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingConcertEventsInCityRow{}
	for rows.Next() {
		var i GetUpcomingConcertEventsInCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.VenueID,
			&i.Genres,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceCurrency,
			&i.TicketUrl,
			&i.Description,
			&i.Status,
			&i.AgeRestriction,
			&i.Provider,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueStreet,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCountry,
			&i.VenuePostal,
			&i.VenueCapacity,
			&i.InterestedUserIds,
			&i.GoingUserIds,
			&i.LookingForGroupUserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const getUserByUsernameWithPassword = `-- name: GetUserByUsernameWithPassword :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsernameWithPassword(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameWithPassword, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const insertSpotifyTopArtistSnapshot = `-- name: InsertSpotifyTopArtistSnapshot :exec
INSERT INTO spotify_top_artist_snapshots (user_id, fetched_at, range, item_rank, spotify_artist_id, name, genres, popularity, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, range, item_rank) DO UPDATE SET
  spotify_artist_id = EXCLUDED.spotify_artist_id,
  name = EXCLUDED.name,
  genres = EXCLUDED.genres,
  popularity = EXCLUDED.popularity,
  image_url = EXCLUDED.image_url,
  fetched_at = EXCLUDED.fetched_at
`

type InsertSpotifyTopArtistSnapshotParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	Range           string             `json:"range"`
	ItemRank        int32              `json:"item_rank"`
	SpotifyArtistID string             `json:"spotify_artist_id"`
	Name            string             `json:"name"`
	Genres          []string           `json:"genres"`
	Popularity      pgtype.Int4        `json:"popularity"`
	ImageUrl        pgtype.Text        `json:"image_url"`
}

func (q *Queries) InsertSpotifyTopArtistSnapshot(ctx context.Context, arg InsertSpotifyTopArtistSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSpotifyTopArtistSnapshot,
		arg.UserID,
		arg.FetchedAt,
		arg.Range,
		arg.ItemRank,
		arg.SpotifyArtistID,
		arg.Name,
		arg.Genres,
		arg.Popularity,
		arg.ImageUrl,
	)
	return err
}

const insertSpotifyTopTrackSnapshot = `-- name: InsertSpotifyTopTrackSnapshot :exec
INSERT INTO spotify_top_track_snapshots (user_id, fetched_at, range, item_rank, spotify_track_id, name, artist_names, artist_ids, album_name, album_id, popularity, preview_url, duration_ms, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (user_id, range, item_rank) DO UPDATE SET
  spotify_track_id = EXCLUDED.spotify_track_id,
  name = EXCLUDED.name,
  artist_names = EXCLUDED.artist_names,
  artist_ids = EXCLUDED.artist_ids,
  album_name = EXCLUDED.album_name,
  album_id = EXCLUDED.album_id,
  popularity = EXCLUDED.popularity,
  preview_url = EXCLUDED.preview_url,
  duration_ms = EXCLUDED.duration_ms,
  image_url = EXCLUDED.image_url,
  fetched_at = EXCLUDED.fetched_at
`

type InsertSpotifyTopTrackSnapshotParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	Range          string             `json:"range"`
	ItemRank       int32              `json:"item_rank"`
	SpotifyTrackID string             `json:"spotify_track_id"`
	Name           string             `json:"name"`
	ArtistNames    []string           `json:"artist_names"`
	ArtistIds      []string           `json:"artist_ids"`
	AlbumName      pgtype.Text        `json:"album_name"`
	AlbumID        pgtype.Text        `json:"album_id"`
	Popularity     pgtype.Int4        `json:"popularity"`
	PreviewUrl     pgtype.Text        `json:"preview_url"`
	DurationMs     pgtype.Int4        `json:"duration_ms"`
	ImageUrl       pgtype.Text        `json:"image_url"`
}

func (q *Queries) InsertSpotifyTopTrackSnapshot(ctx context.Context, arg InsertSpotifyTopTrackSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSpotifyTopTrackSnapshot,
		arg.UserID,
		arg.FetchedAt,
		arg.Range,
		arg.ItemRank,
		arg.SpotifyTrackID,
		arg.Name,
		arg.ArtistNames,
		arg.ArtistIds,
		arg.AlbumName,
		arg.AlbumID,
		arg.Popularity,
		arg.PreviewUrl,
		arg.DurationMs,
		arg.ImageUrl,
	)
	return err
}

const markPasswordResetTokenAsUsed = `-- name: MarkPasswordResetTokenAsUsed :exec
UPDATE password_reset_tokens 
SET used = TRUE 
WHERE token = $1
`

func (q *Queries) MarkPasswordResetTokenAsUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenAsUsed, token)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET first_name = $1, last_name = $2, email = $3
WHERE id = $4
RETURNING id, username, email, first_name, last_name, password_hash, created_at, updated_at, program, graduation_year
`

type UpdateUserParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Program,
		&i.GraduationYear,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users 
SET password_hash = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, username, email
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

type UpdateUserPasswordRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i UpdateUserPasswordRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const upsertConcertArtist = `-- name: UpsertConcertArtist :one
INSERT INTO concert_artists (id, name, genres)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    genres = EXCLUDED.genres,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, genres, created_at, updated_at
`

type UpsertConcertArtistParams struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Genres []string `json:"genres"`
}

func (q *Queries) UpsertConcertArtist(ctx context.Context, arg UpsertConcertArtistParams) (ConcertArtist, error) {
	row := q.db.QueryRow(ctx, upsertConcertArtist, arg.ID, arg.Name, arg.Genres)
	var i ConcertArtist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConcertEvent = `-- name: UpsertConcertEvent :one
INSERT INTO concert_events (id, name, event_date, venue_id, genres, price_min, price_max, price_currency, ticket_url, description, status, age_restriction, provider, external_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    event_date = EXCLUDED.event_date,
    venue_id = EXCLUDED.venue_id,
    genres = EXCLUDED.genres,
    price_min = EXCLUDED.price_min,
    price_max = EXCLUDED.price_max,
    price_currency = EXCLUDED.price_currency,
    ticket_url = EXCLUDED.ticket_url,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    age_restriction = EXCLUDED.age_restriction,
    provider = EXCLUDED.provider,
    external_url = EXCLUDED.external_url,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, event_date, venue_id, genres, price_min, price_max, price_currency, ticket_url, description, status, age_restriction, provider, external_url, created_at, updated_at
`

type UpsertConcertEventParams struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	EventDate      pgtype.Timestamp `json:"event_date"`
	VenueID        pgtype.Text      `json:"venue_id"`
	Genres         []string         `json:"genres"`
	PriceMin       pgtype.Numeric   `json:"price_min"`
	PriceMax       pgtype.Numeric   `json:"price_max"`
	PriceCurrency  pgtype.Text      `json:"price_currency"`
	TicketUrl      pgtype.Text      `json:"ticket_url"`
	Description    pgtype.Text      `json:"description"`
	Status         string           `json:"status"`
	AgeRestriction pgtype.Text      `json:"age_restriction"`
	Provider       string           `json:"provider"`
	ExternalUrl    pgtype.Text      `json:"external_url"`
}

func (q *Queries) UpsertConcertEvent(ctx context.Context, arg UpsertConcertEventParams) (ConcertEvent, error) {
	row := q.db.QueryRow(ctx, upsertConcertEvent,
		arg.ID,
		arg.Name,
		arg.EventDate,
		arg.VenueID,
		arg.Genres,
		arg.PriceMin,
		arg.PriceMax,
		arg.PriceCurrency,
		arg.TicketUrl,
		arg.Description,
		arg.Status,
		arg.AgeRestriction,
		arg.Provider,
		arg.ExternalUrl,
	)
	var i ConcertEvent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.VenueID,
		&i.Genres,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceCurrency,
		&i.TicketUrl,
		&i.Description,
		&i.Status,
		&i.AgeRestriction,
		&i.Provider,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventArtist = `-- name: UpsertEventArtist :exec
INSERT INTO concert_event_artists (event_id, artist_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, artist_id) DO UPDATE SET
    role = EXCLUDED.role
`

type UpsertEventArtistParams struct {
	EventID  string      `json:"event_id"`
	ArtistID string      `json:"artist_id"`
	Role     pgtype.Text `json:"role"`
}

func (q *Queries) UpsertEventArtist(ctx context.Context, arg UpsertEventArtistParams) error {
	_, err := q.db.Exec(ctx, upsertEventArtist, arg.EventID, arg.ArtistID, arg.Role)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec

INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent, last_used_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (endpoint) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  p256dh = EXCLUDED.p256dh,
  auth = EXCLUDED.auth,
  user_agent = EXCLUDED.user_agent,
  last_used_at = NOW(),
  updated_at = NOW()
`

type UpsertPushSubscriptionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Endpoint  string      `json:"endpoint"`
	P256dh    string      `json:"p256dh"`
	Auth      string      `json:"auth"`
	UserAgent pgtype.Text `json:"user_agent"`
}

// =======================
// Web Push Subscriptions
// =======================
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	return err
}

const upsertSpotifyTokens = `-- name: UpsertSpotifyTokens :exec

INSERT INTO spotify_tokens (user_id, access_token, refresh_token_encrypted, expires_at, scope, token_type)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, 'Bearer'))
ON CONFLICT (user_id) DO UPDATE SET
    access_token = EXCLUDED.access_token,
    refresh_token_encrypted = EXCLUDED.refresh_token_encrypted,
    expires_at = EXCLUDED.expires_at,
    scope = EXCLUDED.scope,
    token_type = EXCLUDED.token_type,
    updated_at = NOW()
`

type UpsertSpotifyTokensParams struct {
	UserID                uuid.UUID          `json:"user_id"`
	AccessToken           string             `json:"access_token"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Scope                 pgtype.Text        `json:"scope"`
	TokenType             interface{}        `json:"token_type"`
}

// =======================
// Spotify Tokens
// =======================
func (q *Queries) UpsertSpotifyTokens(ctx context.Context, arg UpsertSpotifyTokensParams) error {
	_, err := q.db.Exec(ctx, upsertSpotifyTokens,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshTokenEncrypted,
		arg.ExpiresAt,
		arg.Scope,
		arg.TokenType,
	)
	return err
}

const upsertUserConcertEventInterest = `-- name: UpsertUserConcertEventInterest :exec
INSERT INTO user_concert_event_interest (user_id, event_id, interest_status)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, event_id)
DO UPDATE SET interest_status = EXCLUDED.interest_status, updated_at = NOW()
`

type UpsertUserConcertEventInterestParams struct {
	UserID         uuid.UUID `json:"user_id"`
	EventID        string    `json:"event_id"`
	InterestStatus string    `json:"interest_status"`
}

func (q *Queries) UpsertUserConcertEventInterest(ctx context.Context, arg UpsertUserConcertEventInterestParams) error {
	_, err := q.db.Exec(ctx, upsertUserConcertEventInterest, arg.UserID, arg.EventID, arg.InterestStatus)
	return err
}

const upsertVenue = `-- name: UpsertVenue :one

INSERT INTO venues (id, name, street, city, state, country, postal, capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    street = EXCLUDED.street,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    country = EXCLUDED.country,
    postal = EXCLUDED.postal,
    capacity = EXCLUDED.capacity,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, street, city, state, country, postal, capacity, created_at, updated_at
`

type UpsertVenueParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Street   pgtype.Text `json:"street"`
	City     string      `json:"city"`
	State    pgtype.Text `json:"state"`
	Country  string      `json:"country"`
	Postal   pgtype.Text `json:"postal"`
	Capacity pgtype.Int4 `json:"capacity"`
}

// =======================
// Concert Events
// =======================
func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, upsertVenue,
		arg.ID,
		arg.Name,
		arg.Street,
		arg.City,
		arg.State,
		arg.Country,
		arg.Postal,
		arg.Capacity,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.State,
		&i.Country,
		&i.Postal,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
