// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addUserArtist = `-- name: AddUserArtist :exec
INSERT INTO user_artists (user_id, artist_id, rank)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, artist_id, rank) DO NOTHING
`

type AddUserArtistParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ArtistID int32     `json:"artist_id"`
	Rank     int16     `json:"rank"`
}

// User-Artist relationship queries
func (q *Queries) AddUserArtist(ctx context.Context, arg AddUserArtistParams) error {
	_, err := q.db.ExecContext(ctx, addUserArtist, arg.UserID, arg.ArtistID, arg.Rank)
	return err
}

const clearUserArtists = `-- name: ClearUserArtists :exec
DELETE FROM user_artists WHERE user_id = $1
`

func (q *Queries) ClearUserArtists(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearUserArtists, userID)
	return err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

// Artist queries
func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (user_id, feedback_text)
VALUES ($1, $2)
RETURNING id, user_id, feedback_text, created_at, updated_at
`

type CreateFeedbackParams struct {
	UserID       uuid.UUID `json:"user_id"`
	FeedbackText string    `json:"feedback_text"`
}

// Feedback queries
func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback, arg.UserID, arg.FeedbackText)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedbackText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, first_name, last_name, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, first_name, last_name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const findSimilarUsers = `-- name: FindSimilarUsers :many
SELECT
  u1.username,
  u1.first_name,
  u1.last_name,
  (SELECT array_agg(a1.name ORDER BY ua1.rank ASC)
   FROM user_artists ua1
   JOIN artists a1 ON ua1.artist_id = a1.id
   WHERE ua1.user_id = u1.id) AS artists,
  spearman_distance(
    (SELECT array_agg(a1.name ORDER BY ua1.rank ASC)
     FROM user_artists ua1
     JOIN artists a1 ON ua1.artist_id = a1.id
     WHERE ua1.user_id = u1.id),
    (SELECT array_agg(a2.name ORDER BY ua2.rank ASC)
     FROM users u2
     JOIN user_artists ua2 ON u2.id = ua2.user_id
     JOIN artists a2 ON ua2.artist_id = a2.id
     WHERE u2.username = $1)
  ) AS distance
FROM users u1
WHERE u1.username != $1
  AND EXISTS (SELECT 1 FROM user_artists WHERE user_id = u1.id)
ORDER BY distance ASC
LIMIT 10
`

type FindSimilarUsersRow struct {
	Username  string      `json:"username"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Artists   interface{} `json:"artists"`
	Distance  float64     `json:"distance"`
}

func (q *Queries) FindSimilarUsers(ctx context.Context, username string) ([]FindSimilarUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, findSimilarUsers, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarUsersRow{}
	for rows.Next() {
		var i FindSimilarUsersRow
		if err := rows.Scan(
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Artists,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllArtists = `-- name: GetAllArtists :many
SELECT id, name, created_at FROM artists ORDER BY name
`

func (q *Queries) GetAllArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFeedback = `-- name: GetAllFeedback :many
SELECT f.id, f.user_id, f.feedback_text, f.created_at, f.updated_at, u.username, u.first_name, u.last_name
FROM feedback f
JOIN users u ON f.user_id = u.id
ORDER BY f.created_at DESC
LIMIT $1
`

type GetAllFeedbackRow struct {
	ID           int32        `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	FeedbackText string       `json:"feedback_text"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	Username     string       `json:"username"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
}

func (q *Queries) GetAllFeedback(ctx context.Context, limit int32) ([]GetAllFeedbackRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeedback, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllFeedbackRow{}
	for rows.Next() {
		var i GetAllFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedbackText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at FROM users ORDER BY created_at
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, created_at FROM artists WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtistByID(ctx context.Context, id int32) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, created_at FROM artists WHERE name = $1 LIMIT 1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getArtistUsers = `-- name: GetArtistUsers :many
SELECT u.id, u.username, u.email, u.first_name, u.last_name, u.created_at, u.updated_at
FROM users u
JOIN user_artists ua ON u.id = ua.user_id
WHERE ua.artist_id = $1
ORDER BY u.username
`

type GetArtistUsersRow struct {
	ID        uuid.UUID    `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetArtistUsers(ctx context.Context, artistID int32) ([]GetArtistUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getArtistUsers, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArtistUsersRow{}
	for rows.Next() {
		var i GetArtistUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackByUser = `-- name: GetFeedbackByUser :many
SELECT id, user_id, feedback_text, created_at, updated_at FROM feedback
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFeedbackByUser(ctx context.Context, userID uuid.UUID) ([]Feedback, error) {
	rows, err := q.db.QueryContext(ctx, getFeedbackByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedbackText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserArtists = `-- name: GetUserArtists :many
SELECT a.id, a.name, a.created_at
FROM artists a
JOIN user_artists ua ON a.id = ua.artist_id
WHERE ua.user_id = $1
ORDER BY a.name
`

func (q *Queries) GetUserArtists(ctx context.Context, userID uuid.UUID) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getUserArtists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameWithPassword = `-- name: GetUserByUsernameWithPassword :one
SELECT id, username, email, first_name, last_name, password_hash, created_at, updated_at 
FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsernameWithPassword(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameWithPassword, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersWithArtists = `-- name: GetUsersWithArtists :many
SELECT 
    u.id, u.username, u.email, u.first_name, u.last_name,
    COALESCE(array_agg(a.name) FILTER (WHERE a.name IS NOT NULL), '{}') as artist_names
FROM users u
LEFT JOIN user_artists ua ON u.id = ua.user_id
LEFT JOIN artists a ON ua.artist_id = a.id
GROUP BY u.id, u.username, u.email, u.first_name, u.last_name
ORDER BY u.username
`

type GetUsersWithArtistsRow struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	ArtistNames interface{} `json:"artist_names"`
}

// Matching queries
func (q *Queries) GetUsersWithArtists(ctx context.Context) ([]GetUsersWithArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithArtistsRow{}
	for rows.Next() {
		var i GetUsersWithArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ArtistNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserArtist = `-- name: RemoveUserArtist :exec
DELETE FROM user_artists WHERE user_id = $1 AND artist_id = $2
`

type RemoveUserArtistParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ArtistID int32     `json:"artist_id"`
}

func (q *Queries) RemoveUserArtist(ctx context.Context, arg RemoveUserArtistParams) error {
	_, err := q.db.ExecContext(ctx, removeUserArtist, arg.UserID, arg.ArtistID)
	return err
}

const searchArtists = `-- name: SearchArtists :many
SELECT id, name, created_at FROM artists 
WHERE LOWER(name) LIKE LOWER($1) 
ORDER BY 
  CASE 
    WHEN LOWER(name) = LOWER($2) THEN 1
    WHEN LOWER(name) LIKE LOWER($3) THEN 2
    ELSE 3
  END,
  LENGTH(name),
  name
LIMIT $4
`

type SearchArtistsParams struct {
	Lower   string `json:"lower"`
	Lower_2 string `json:"lower_2"`
	Lower_3 string `json:"lower_3"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, searchArtists,
		arg.Lower,
		arg.Lower_2,
		arg.Lower_3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserArtists = `-- name: SetUserArtists :exec
WITH new_artists AS (
    INSERT INTO artists (name)
    SELECT unnest($2::text[])
    ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
    RETURNING id, name
),
ranked_artists AS (
    SELECT 
        a.id,
        a.name,
        ($3::int[])[array_position($2::text[], a.name)] as rank
    FROM new_artists a
)
INSERT INTO user_artists (user_id, artist_id, rank)
SELECT $1, id, rank FROM ranked_artists
ON CONFLICT (user_id, artist_id) DO UPDATE SET rank = EXCLUDED.rank
`

type SetUserArtistsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 []string  `json:"column_2"`
	Column3 []int32   `json:"column_3"`
}

func (q *Queries) SetUserArtists(ctx context.Context, arg SetUserArtistsParams) error {
	_, err := q.db.ExecContext(ctx, setUserArtists, arg.UserID, pq.Array(arg.Column2), pq.Array(arg.Column3))
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET first_name = $2, last_name = $3, email = $4
WHERE id = $1
RETURNING id, username, email, first_name, last_name, password_hash, created_at, updated_at
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
