// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// User-Artist relationship queries
	AddUserArtist(ctx context.Context, arg AddUserArtistParams) error
	ClearUserArtists(ctx context.Context, userID uuid.UUID) error
	// Artist queries
	CreateArtist(ctx context.Context, name string) (Artist, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FindSimilarUsers(ctx context.Context, username string) ([]FindSimilarUsersRow, error)
	GetAllArtists(ctx context.Context) ([]Artist, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetArtistByID(ctx context.Context, id int32) (Artist, error)
	GetArtistByName(ctx context.Context, name string) (Artist, error)
	GetArtistUsers(ctx context.Context, artistID int32) ([]GetArtistUsersRow, error)
	GetUserArtists(ctx context.Context, userID uuid.UUID) ([]Artist, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByUsernameWithPassword(ctx context.Context, username string) (User, error)
	// Matching queries
	GetUsersWithArtists(ctx context.Context) ([]GetUsersWithArtistsRow, error)
	RemoveUserArtist(ctx context.Context, arg RemoveUserArtistParams) error
	SetUserArtists(ctx context.Context, arg SetUserArtistsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
