// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// =======================
	// User-Artist relations
	// =======================
	// FIX: conflict target must be a unique/PK constraint. Your table has PK (user_id, artist_id)
	AddUserArtist(ctx context.Context, arg AddUserArtistParams) error
	ChamferSimilarityByIDs(ctx context.Context, arg ChamferSimilarityByIDsParams) (float64, error)
	ChamferSimilarityByNames(ctx context.Context, arg ChamferSimilarityByNamesParams) (float64, error)
	ClearUserArtists(ctx context.Context, userID uuid.UUID) error
	// =======================
	// Artists
	// =======================
	CreateArtist(ctx context.Context, name string) (Artist, error)
	// (If you also want the :by-user-id variant, keep your FindSimilarUsersChamferByUserID below unchanged.)
	// Feedback queries
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	// =======================
	// Users
	// =======================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// =======================
	// Nearest neighbors (Chamfer-based)
	// Replace old PWO query with Chamfer under the same exported name
	// =======================
	// :username => the anchor profile
	// :limit_n  => how many matches to return
	FindSimilarUsers(ctx context.Context, arg FindSimilarUsersParams) ([]FindSimilarUsersRow, error)
	GetAllArtists(ctx context.Context) ([]Artist, error)
	GetAllFeedback(ctx context.Context, lim int32) ([]GetAllFeedbackRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetArtistByID(ctx context.Context, id int32) (Artist, error)
	GetArtistByName(ctx context.Context, name string) (Artist, error)
	GetArtistUsers(ctx context.Context, artistID int32) ([]GetArtistUsersRow, error)
	GetFeedbackByUser(ctx context.Context, userID uuid.UUID) ([]Feedback, error)
	GetUserArtists(ctx context.Context, userID uuid.UUID) ([]GetUserArtistsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByUsernameWithPassword(ctx context.Context, username string) (User, error)
	// =======================
	// Matching helpers / reports
	// =======================
	GetUsersWithArtists(ctx context.Context) ([]GetUsersWithArtistsRow, error)
	PairwiseArtistSimilarityByIDs(ctx context.Context, artist1ID int32) (int32, error)
	// =======================
	// New similarity APIs (artist + set)
	// =======================
	PairwiseArtistSimilarityByNames(ctx context.Context, arg PairwiseArtistSimilarityByNamesParams) (PairwiseArtistSimilarityByNamesRow, error)
	RemoveUserArtist(ctx context.Context, arg RemoveUserArtistParams) error
	SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]Artist, error)
	SetUserArtists(ctx context.Context, arg SetUserArtistsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserChamferSimilarity(ctx context.Context, arg UserChamferSimilarityParams) (float64, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
