// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// (If you also want the :by-user-id variant, keep your FindSimilarUsersChamferByUserID below unchanged.)
	// Feedback queries
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	// =======================
	// Password Reset Tokens
	// =======================
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	// =======================
	// Users
	// =======================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredPasswordResetTokens(ctx context.Context) error
	DeleteOldConcertEvents(ctx context.Context, cutoffDate pgtype.Timestamp) error
	DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	DeleteSpotifyTopArtistSnapshotForRange(ctx context.Context, arg DeleteSpotifyTopArtistSnapshotForRangeParams) error
	DeleteSpotifyTopTrackSnapshotForRange(ctx context.Context, arg DeleteSpotifyTopTrackSnapshotForRangeParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserConcertEventInterest(ctx context.Context, arg DeleteUserConcertEventInterestParams) error
	DeleteUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error
	// =======================
	// Spotify Top Items
	// =======================
	// Given an anchor user (user_id) and a Spotify time range, compute similarity to other users
	// based on overlapping top artists in the latest snapshot for that range per user.
	// Similarity uses a rank-weighted reciprocal scheme: weight = 1 / (r_anchor + r_other)
	// and aggregated similarity = SUM(weights) over all overlapping artist_ids.
	// Returns top N other users ordered by descending similarity. Ties resolved by created_at asc.
	// Also returns the overlapping artist names and their anchor/other ranks encoded as JSON.
	// Parameters:
	//   user_id UUID          -> anchor user
	//   range   TEXT          -> spotify range ('short_term'|'medium_term'|'long_term')
	//   limit_n INT           -> maximum similar users to return
	//   top_n   INT           -> consider only top N ranked items per user
	// Notes:
	//   * We restrict snapshots to only the most recent fetched_at per user per range using the views.
	//   * We filter out users with zero overlap.
	//   * JSON structure for overlaps: [{"spotify_artist_id":"...","name":"...","anchor_rank":1,"other_rank":2}]
	FindTopNSimilarUsersBySpotifyArtists(ctx context.Context, arg FindTopNSimilarUsersBySpotifyArtistsParams) ([]FindTopNSimilarUsersBySpotifyArtistsRow, error)
	// Similar to artist similarity but operates on track snapshots.
	FindTopNSimilarUsersBySpotifyTracks(ctx context.Context, arg FindTopNSimilarUsersBySpotifyTracksParams) ([]FindTopNSimilarUsersBySpotifyTracksRow, error)
	GetAllFeedback(ctx context.Context, lim int32) ([]GetAllFeedbackRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAnyPushSubscriptions(ctx context.Context, lim int32) ([]PushSubscription, error)
	GetChicagoEventsCountWithArtistSearch(ctx context.Context, arg GetChicagoEventsCountWithArtistSearchParams) (int64, error)
	GetChicagoEventsWithArtistSearch(ctx context.Context, arg GetChicagoEventsWithArtistSearchParams) ([]GetChicagoEventsWithArtistSearchRow, error)
	GetConcertEventByID(ctx context.Context, id string) (GetConcertEventByIDRow, error)
	// Optional interest_status filter: if provided (non-empty), counts events having at least one user with that status
	GetConcertEventCount(ctx context.Context, interestStatus interface{}) (int64, error)
	GetConcertEventsInDateRange(ctx context.Context, arg GetConcertEventsInDateRangeParams) ([]GetConcertEventsInDateRangeRow, error)
	// Returns events within date range plus associated venue, artists, and user interest buckets
	GetConcertEventsInDateRangeWithInterest(ctx context.Context, arg GetConcertEventsInDateRangeWithInterestParams) ([]GetConcertEventsInDateRangeWithInterestRow, error)
	GetEventArtists(ctx context.Context, eventID string) ([]GetEventArtistsRow, error)
	GetEventsForArtist(ctx context.Context, arg GetEventsForArtistParams) ([]GetEventsForArtistRow, error)
	GetFeedbackByUser(ctx context.Context, userID uuid.UUID) ([]Feedback, error)
	GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetPushSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]PushSubscription, error)
	GetSpotifyTokensByUser(ctx context.Context, userID uuid.UUID) (SpotifyToken, error)
	GetUpcomingConcertEventsInCity(ctx context.Context, arg GetUpcomingConcertEventsInCityParams) ([]GetUpcomingConcertEventsInCityRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByUsernameWithPassword(ctx context.Context, username string) (User, error)
	InsertSpotifyTopArtistSnapshot(ctx context.Context, arg InsertSpotifyTopArtistSnapshotParams) error
	InsertSpotifyTopTrackSnapshot(ctx context.Context, arg InsertSpotifyTopTrackSnapshotParams) error
	MarkPasswordResetTokenAsUsed(ctx context.Context, token string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error)
	UpsertConcertArtist(ctx context.Context, arg UpsertConcertArtistParams) (ConcertArtist, error)
	UpsertConcertEvent(ctx context.Context, arg UpsertConcertEventParams) (ConcertEvent, error)
	UpsertEventArtist(ctx context.Context, arg UpsertEventArtistParams) error
	// =======================
	// Web Push Subscriptions
	// =======================
	UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error
	// =======================
	// Spotify Tokens
	// =======================
	UpsertSpotifyTokens(ctx context.Context, arg UpsertSpotifyTokensParams) error
	UpsertUserConcertEventInterest(ctx context.Context, arg UpsertUserConcertEventInterestParams) error
	// =======================
	// Concert Events
	// =======================
	UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
